### ISSUE TITLE
PSI_VERSION undefinied.

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4public#100]
The `gitversion.h` does `#undef PSI_VERSION` which makes the file `src/bin/psi4/python.cc` fail to build as it needs a `PSI_VERSION`.

What is the idea here? Why no `PSI_VERSION`?

**Comment by SebWouters** [comment]
I just tried to recompile from scratch as well, and got the same error:

Scanning dependencies of target versioned_code
[ 98%] Building CXX object
src/bin/psi4/CMakeFiles/versioned_code.dir/version.cc.o
[ 98%] Building CXX object
src/bin/psi4/CMakeFiles/versioned_code.dir/python.cc.o
/home/seba/psi4public/src/bin/psi4/python.cc(764): error: identifier
"PSI_VERSION" is undefined
      return PSI_VERSION;
             ^

/home/seba/psi4public/src/bin/psi4/python.cc(1217): warning #1011: missing
return statement at end of non-void function "py_psi_get_normalmodes"
  }
  ^

compilation aborted for /home/seba/psi4public/src/bin/psi4/python.cc (code
2)
make[2]: *** [src/bin/psi4/CMakeFiles/versioned_code.dir/python.cc.o] Error
2
make[1]: *** [src/bin/psi4/CMakeFiles/versioned_code.dir/all] Error 2
make: *** [all] Error 2

2015-05-26 10:52 GMT+02:00 wpoely86 <notifications@github.com>:

> The gitversion.h does #undef PSI_VERSION which makes the file
> src/bin/psi4/python.cc fail to build as it needs a PSI_VERSION.
>
> What is the idea here? Why no PSI_VERSION?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/100>.
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Fellow of the Belgian American Educational Foundation
  Princeton University
  (address) Department of Chemistry
            Frick Laboratory 351
            Princeton, NJ 08544, USA
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by wpoely86** [comment]
Maybe consider using something like [Travis Ci](https://travis-ci.org/) to find these kinds of things quickly?

**Comment by loriab** [comment]
This was because (on private) people weren't pulling tags or (on public) because tags weren't getting synced between public and private. I've forcibly synched tags between the repos now and also through 568019b2dfd08703e8236391ade18191cdd8d06d given it a default string, so this can't pop up again.
