### ISSUE TITLE
Open-shell DF-MP2 optimization clarifications

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4public#106]
Footnote [2] of the capabilities table in the manual is a little unclear about what methods are available:

RHF and UHF reference are available, however the latter one should be
requsted from DFOCC module. DF-MP2 is recommended as a faster
alternative.

Update and revise manual.  Check with Ugur about ROHF.  Make appropriate defaults.

**Comment by bozkaya** [comment]
I have revised the footnote.

On Wed, Jul 8, 2015 at 11:53 PM, David Sherrill <notifications@github.com>
wrote:

> Footnote [2] of the capabilities table in the manual is a little unclear
> about what methods are available:
>
> RHF and UHF reference are available, however the latter one should be
> requsted from DFOCC module. DF-MP2 is recommended as a faster
> alternative.
>
> Update and revise manual. Check with Ugur about ROHF. Make appropriate
> defaults.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/106>.
>



-- 
Assoc. Prof. Ugur Bozkaya
Department of Chemistry,
Ataturk University,
25240 Erzurum, Turkey,
Tel: +90 442 231 41 14,
E-mail: ugrbzky@gmail.com,
ugur.bozkaya@atauni.edu.tr.

**Comment by CDSherrill** [comment]
Revised footnote looks good.  Lori will need to check that we run the correct modules by default.
