### ISSUE TITLE
tidy up on sirius

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#112]
- [x] need to redirect docs latest and master on sirius to  on psicode. Many ways how here: https://css-tricks.com/redirect-web-page/ . Perhaps Apache best? I know that's installed. Want to redirect rather than shutdown so that google and co. don't reset the popularity ratings.

- [x] need to tarball the trac website and stuff it somewhere. Not everything was transferred to the wiki, but most everything *useful* migrated.

Should sirius be decommissioned someday,

- [x] tarball up all the old (beta2 onwards) docs builds, establish them on godaddy or something, and relink on psicode.

- [x] shut down trac page

**Comment by lothian** [comment]
Modified sirius.chem.vt.edu sphinxman pages to redirect to 

http://www.psicode.org/psi4manual/master/index.html

Please test at your convenience, loriab.

**Comment by loriab** [comment]
Thanks! The front (index.html) pages work great. The subpages (e.g., http://sirius.chem.vt.edu/psi4manual/master/documentation.html) don't redirect. If ``RedirectMatch 301 /blog(.*) http://www.new-website.com$1`` in `.htaccess` enables subpage redirect, that'd be ideal. If not, front-page only redirect will be quite sufficient.

**Comment by lothian** [comment]
OK, I used the RedirectMatch syntax to force all references to /psi4manual/master into the corresponding pages on psicode.org.  Are there any other versions on that server that need redirects, or just master?

**Comment by psi4** [comment]
Ok, I didn't get the redirect on Chrome until I cleared the cache, but now it works nicely. Firefox, too. I think redirect 'latest' as well as 'master', then that bullet's done, thanks.

**Comment by lothian** [comment]
Done with that bullet, but I think also the other two.  I dumped a tarball of the sirius trac website on psicode.org as trac@sirius.chem.vt.edu.tgz.  In addition, I pulled the docs from the old 4.0b2, 4.0b3, 4.0b4, and 4.0b5 dockers from sirius and moved them into place in html/psi4manual on psicode.org.

Please take a look and see that you're in agreement with all this.  I may then shut down trac on sirius.

**Comment by psi4** [comment]
Docs 4.0b 2, 3, 4 look good, and I changed ``release_notes.php`` to point to them locally on psicode. Beta5 persistently redirects to master, and looking at the file sizes, there may be a link instead of a file somewhere.

```bash
psicode@www.psicode.org:p3nlhftpg153:/var/chroot/home/content/55/9100355/html: ll psi4manual/*/index.html
-rw-r--r-- 1 psicode inetuser 17284 Aug 25  2013 psi4manual/4.0b2/index.html
-rw-r--r-- 1 psicode inetuser 17642 Apr  5  2013 psi4manual/4.0b3/index.html
-rw-r--r-- 1 psicode inetuser 18464 Mar 20  2014 psi4manual/4.0b4/index.html
-rw-r--r-- 1 psicode inetuser   129 Jul 14 09:16 psi4manual/4.0b5/index.html
-rw-r--r-- 1 psicode inetuser 30363 Jul 13 23:57 psi4manual/master-but-one/index.html
-rw-r--r-- 1 psicode inetuser 30363 Jul 14 12:42 psi4manual/master/index.html
```

I'll untar the trac site just to check.

**Comment by lothian** [comment]
The 4.0b5 issue was my fault, and I've fixed it now.  That was my original attempt at a redirect.

**Comment by psi4** [comment]
Yes, works! That wraps up the documentation shuffling, I think. Provides all the good stuff of the trac page is in the 116MB ``db/trac.db`` file, that tarball looks good, too. Another issue closed, thanks!

**Comment by lothian** [comment]
I've shut down the trac pages of sirius.
