### ISSUE TITLE
stray file 97

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#113]
When running a ``cp()`` calculation, file 97 is left behind. It needs to be preserved at some points in the calc to avoid recomputation, but it shouldn't persist beyond the run.

**Comment by bwb314** [comment]
The issue was in filemanager.cc. Once files were marked to be retained, they were permanently added to a list of retained file paths. I have added code to remove files from this list once they are marked to be discarded.

**Comment by loriab** [comment]
@bwb314 fixed this with https://github.com/psi4/psi4/commit/a5facd8209d05da9beefc0d097acb3977146f3a2
