### ISSUE TITLE
efp finalization

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#115]
Thanks to @andysim, we're very close to efp-scf energies in working order. Last remaining order of business is efp-scf with spherical basis sets. Once again, Andy fixed this, but now it's breaking later in the code. The tests/libefp/qmefp-moldomains part 5 should fail at compare_values (b/c the value is for puream false) but it should complete sucessfully instead of segfaulting as it does at present. Needs a gdb analysis to find where in the scf it's breaking, then repair from there. At one point, q-chem didn't do puream true basis sets with efp at all. If that limitation is no longer in place, would be great to get a comparison value from q-chem and add that test case.

**Comment by loriab** [comment]
here's a minimal input for debugging

```
molecule {
  efp c6h6  0.0 0.0 0.0   0.0 0.0 0.0
  --
  O  4.0   0.0   0.0
  H  4.7   0.7   0.0
  H  3.3  -0.7   0.0
  --
  efp h2o  -4.0 0.0 0.0   0.0 0.0 0.0
}

set basis cc-pvdz
energy('scf')
```

**Comment by andysim** [comment]
Thanks, Lori.  I’m still tied up with work in St Louis, but will get on this as soon as I get back to UT.  It should be easy to find, I hope.

**Comment by loriab** [comment]
Sorry, @andysim . I meant that post as a prod to me rather than a burden to you. That said, I did look at it today and the problem is at https://github.com/psi4/psi4public/blob/master/src/lib/libefp_solver/efp_solver.cc#L301 where, for spherical basis set, the dimensions of ``intmats`` don't match ``Da``. I applied changes in 05737ea5ea64943c085751f43b432dabc62e57cf , and that does fix the segfault for sph while not changing the results for cart basis sets. Haven't checked vs. Q-Chem yet, but could you look at that commit and see if it looks sensible?

**Comment by loriab** [comment]
The commit above was probably necessary (solves the segfault) but not sufficient, as spherical basis wavefunction polarization energies still off. Necessary analogous q-chem calcs run and test prepared such that when https://github.com/psi4/psi4public/blob/master/tests/libefp/libefp-qchem-qmefp-puream-sp /input.dat passes, this issue is fixed.

**Comment by andysim** [comment]
I'm about to commit the appropriate changes; it was just a silly dimensioning issue, as expected.  Sorry for completely forgetting about this, and thanks to @CDSherrill for reminding me.  Would you mind running it through your inputs as an extra set of checks, @loriab?  Also, would you mind making the necessary cleanup in tests/libefp?  I can get to it later if not.

**Comment by CDSherrill** [comment]
Woohoo!  Fantastic!

**Comment by loriab** [comment]
Yay, indeed! Just checked the test cases and all 5 pass. Added the last output.ref with 0ee93a3 . Did you have any other tests/libefp cleanup in mind?

**Comment by CDSherrill** [comment]
Looks like the manual sections are already there, so I think this is fully completed!

**Comment by andysim** [comment]
Sorry, @loriab, I didn't see your previous message announcing the cleanup and introduction of the new qmefp-puream test.  I think it's all good as-is, but the folders qc-scfefp-sp1 and qc-scfefp-sp2 appear to not contain an input.dat.  Should they be deleted?

**Comment by andysim** [comment]
Scratch that; I just looked on the GitHub version and they're already gone.  I guess I just have some stale folders around as a result of not doing a fresh checkout for a while.  I think we're all done with this now.

**Comment by loriab** [comment]
Ok, yeah, I have many misc. dirs in my tests/libefp, too. But the github repo looks clean.
