### ISSUE TITLE
Cube file test case and documentation

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4public#116]
Francesco recently checked in Rob's cube file generation code.  Make sure there is a corresponding test case (maybe it's more of a sample, since not sure how to test that ... can at least make sure it runs, anyway).  Also make sure there is documentation.

**Comment by fevangelista** [comment]
I just added a test case. Documentation is already in place, but it should probably be expanded with instructions on how to use .cube files.

**Comment by fevangelista** [comment]
I need some help with the cube prop test case.  The way I set the test case requires comparing the cube files generated with some reference cube files, stored in tests/cubeprop.  How can I copy these files in the directory in which tests are executed?

**Comment by ryanmrichard** [comment]
I didn't realized you had opened an issue, I fixed it for you in commit 42345de37df6827356fe7215aa2745b36c946d9e.  If you are still interested look at tests/cubeprop/CMakeLists.txt basically the command is:
```cmake
 file(copy <name> DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```
