### ISSUE TITLE
fix failing test case fd-freq-energy-large

### ISSUE THREAD

**Issue by psi4** [psi4/psi4public#123]

**Comment by kannon92** [comment]
This test case does not work for my mac.

**Comment by ryanmrichard** [comment]
This test case uses analytic frequencies and requests that a three and five point finite-difference calculation is run.  The original comparisons were a bit tight (0.1 and 0.001 cm^-1).  I switched the reference data to finite difference values and loosened the tolerance check to a wavenumber.

903bb0e380ecf8304875409b73fb19d69c6f393a
