### ISSUE TITLE
Tests fail on Fedora rawhide

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4public#13]
Quicktests fail on Fedora rawhide i686. The test case output is

Testing pywrap-freq-e-sowreap...
Performing finite difference calculations by energies
 13 displacements needed.
 Computation complete.
        Frequencies.......................................................PASSED
        ZPVE..............................................................PASSED
        SP energy.........................................................PASSED
        SP NRE............................................................PASSED
        SP NRE............................................................PASSED
        SP NRE............................................................PASSED
Testing cc8...
\tFAILED
Testing cc18...
        Nuclear repulsion energy..........................................PASSED
        SCF energy........................................................PASSED
        CCSD correlation energy...........................................PASSED
        CCSD total energy.................................................PASSED
\tFAILED
Testing cc19...
\tFAILED
Testing cc28...
\tFAILED
Testing cc49...
\tFAILED

The cc??.test files are empty, but the output.dat's seem sane...

**Comment by psi4** [comment]
Any one with a Fedora box, please confirm or deny.

**Comment by bennybp** [comment]
Those tests pass for me on Fedora 21 x86_64

**Comment by loriab** [comment]
Great, close it, or tell me to.
