### ISSUE TITLE
Some issues in public can be closed.  

### ISSUE THREAD

**Issue by kannon92** [psi4/psi4public#146]
- Issue 92
- Possibly Issue 98 - Problem with DMRG computing all the integrals.  Not really an issue.
- Issue 69 -> Closed
- Issue 63 -> seems done. Need to use SAD guess.
- Issue 58 -> Forgot a basis set.
- Issue 67 -> No one ever answered.
- Issue 65 -> Not really an issue/bug
- Issue 57 -> could be closed.  More of a question?
- Issue 55 -> solved
- Issue 53 -> really old way of compiling
- Issue 40 -> I think it is done.
- Issue 36 -> Could be done.

Please look some of these over and see if they can be closed.

**Comment by CDSherrill** [comment]
Thanks for the help.  I've reviewed several of these.
