### ISSUE TITLE
All ROHF-based test cases are failing, e.g. cc10

### ISSUE THREAD

**Issue by lothian** [psi4/psi4public#148]
I've run tests on both Linux and Mac systems to confirm this behavior.

**Comment by psi4** [comment]
Yes, I see that, too. Perhaps has to do with af75ca066155cfb7a3c63ad9c21dd3953adbff84 commit for https://github.com/psi4/psi4public/issues/107 that I approved too hastily. Will investigate.

**Comment by loriab** [comment]
b8b267339fc18dfa77b3f3d7c3306eb10a81be4a should have fixed this.
