### ISSUE TITLE
periodic systems

### ISSUE THREAD

**Issue by dellelce** [psi4/psi4public#151]
Is there any plan to support periodic systems?

Thanks,
Antonio

**Comment by ryanmrichard** [comment]
It's on my todo list, but a long way from realization so it's not going to happen anytime soon.  VASP and Crystal are the usual gotos for this sort of thing.

**Comment by SebWouters** [comment]
There's also a lingering plan (perhaps for later this summer, when a few
other projects are finished) to write a GPLv2-licensed periodic HF integral
C-library in the Chan group: https://github.com/SebWouters/PauliNG.
The idea is to be a simple and lightweight library to provide integrals for
post-HF calculations in periodic systems. Currently, we use mainly VASP
here by fitting Gaussian ERI with a quadrature of plane waves.




2015-07-20 9:54 GMT-04:00 Ryan Richard <notifications@github.com>:

> It's on my todo list, but a long way from realization so it's not going to
> happen anytime soon. VASP and Crystal are the usual gotos for this sort of
> thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/151#issuecomment-122892690>.
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Fellow of the Belgian American Educational Foundation
  Princeton University
  (address) Department of Chemistry
            Frick Laboratory 351
            Princeton, NJ 08544, USA
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by ryanmrichard** [comment]
I moved this over to the new forum, in the feature request section.  It's URL is supposed to be:
http://forums.psicode.org ,but that seems to not be working on quite a few platforms.  In the meantime use this link: [forums](http://45.55.166.255/t/feature-requests-for-psi4/23/2)

**Comment by lothian** [comment]
By the way, the address should be "forum.psicode.org".  Is that possibly
the problem you guys are encountering with the name?

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by ryanmrichard** [comment]
Neither the plural or the singular work at GATech, so I don't think so.  I've been typing forum.psicode.org, but mistyped the name in the github post.

**Comment by dellelce** [comment]
Unfortunately I don't have access to VASP/CRYSTAL as I am not associated with any institution/company... I am using Octopus for periodic systems now but considering alternatives.
