### ISSUE TITLE
Lacking of library after updating PSI4 from Miniconda

### ISSUE THREAD

**Issue by Hassenky** [psi4/psi4public#154]
A month ago, I installed PSI4 from miniconda. Everything was fine and PSI4 finished a lot of calculations. Recently I have updated PSI4 with the command "conda update psi4" and PSI4 cannot run anymore because of library omission. Using command "conda inspect linkages psi4", I obtained this output:
"not found:
    libgsl.so.0 (not found)
    libgslcblas.so.0 (not found)
    libhdf5.so.10 (not found)
    libhdf5_hl.so.10 (not found)"

What should I do to sovle this problem? It will take me much time if I compile PSI4 and it's dependencies from the beginning.

**Comment by loriab** [comment]
Sorry, I'll fix it in a couple days. For the moment, install an older version from before lastfriday. You can get a list of available versions on the anaconda.org/psi4 and directions for installing a particular version at the docs page.

**Comment by Hassenky** [comment]
Thank you very much Loriab.

**Comment by Hassenky** [comment]
This is error after updating to PSi4 278:
error while loading shared libraries: libifport.so.5: cannot open shared object file: No such file or directory

But I think it can be overcome by adding intel lib into PATH.

Thank you Loriab.

**Comment by loriab** [comment]
Is that the 0.2.278 from 9 hours ago or 20 hours ago? The earlier one I can believe has that problem (as does 0.2.279 if you had caught it before I erased it. But the 278 that's available now I thought was ok. (Note that if you had downloaded the earlier 278, you would need to ``conda remove psi4``, ``rm`` the packages from ``miniconda/pkgs``, and ``conda install psi4`` to force the download and installation of the new 278.)

The ``libifport`` error arises when trying to mix in Fortran code (for dkh) with static compilation (for conda). They're not wanting to play nicely together: https://public.kitware.com/Bug/bug_relationship_graph.php?bug_id=13249&graph=dependency . I can hand-link a mostly static exe but haven't gotten the build system to do it yet.

Please keep on reporting these library errors. I really thought the current conda package should be clean (if Fortran-less).

**Comment by Hassenky** [comment]
I am adding intel ib into the PATH and it is running flawlessly right now. I am checking dkh running and will report here.

**Comment by Hassenky** [comment]
For the  dkh test in sample directory, It is fine. So, it is better if users set environment including intel lib of compiler themselves.

**Comment by loriab** [comment]
Thanks, that's good that it's working for you. But the point of the mostly static conda binary is that users shouldn't need to have Intel MKL themselves. So it's still broken from that perspective.

**Comment by loriab** [comment]
As of 0.2.287, conda binary is building chemps2 and properly downloading dependency hdf5 from defaults and gsl from copy of asmeurer's into psi4 channel.

As of 0.2.291 (42175a9cc2a2ba082c33a676c0bc518125f5f445), conda binary is building dkh and properly linking *static* Fortran libraries so no user PATH manipulations necessary. Checked, but please report if ever otherwise.
