### ISSUE TITLE
Core dump when native symmetry on

### ISSUE THREAD

**Issue by dsirianni** [psi4/psi4public#158]
Attempting to run a geometry optimization on molecule at the B3LYP-D/cc-pVTZ level results in the job crashing whenever native symmetry is left on, but the job runs whenever a symmetry of C1 is specified.  Further digging resulted in finding out that the job is failing because of a core dump.  

Successful input file:

memory 16000 mb

molecule mol {
        units Angstrom
  	symmetry c1 
	N	2.8186748	-1.9320605	0
	C	3.9682155	-1.1155139	0
	N	3.7348961	0.253345	0
	C	2.4718715	0.8928656	0
	C	1.3801963	-0.021916	0
	C	1.6020129	-1.3565857	0
	O	5.0789142	-1.6090969	0
	C	-1.4704537	-1.662531	1.2276603
	C	-0.6314352	-1.2778143	0
	C	-1.4704537	-1.662531	-1.2276603
	N	-2.7456834	-1.1146331	-1.1876558
	N	-2.7456834	-1.1146331	1.1876558
	C	-3.4215193	-0.8181518	0
	C	-0.4410954	0.996968	-1.2925792
	N	-0.5390482	2.3631797	-1.1910976
	C	-0.5061096	3.0855781	0
	N	-0.5390482	2.3631797	1.1910976
	C	-0.4410954	0.996968	1.2925792
	O	-1.0786533	-2.3831691	-2.1082181
	O	-4.5550423	-0.3852824	0
	O	-0.5151061	0.4216645	-2.3608946
	O	-0.5151061	0.4216645	2.3608946
	O	-0.5222264	4.2956077	0
	C	-0.1082324	0.2374533	0
	O	-1.0786533	-2.3831691	2.1082181
	O	2.3952343	2.1158161	0
	O	0.5199028	-2.1266114	0
	C	4.896284	1.1381514	0
	H	5.7890291	0.519171	0
	H	4.8706699	1.7767416	0.8844252
	H	4.8706699	1.7767416	-0.8844252
	C	2.9639859	-3.3851463	0
	H	4.0304645	-3.5950568	0
	H	2.4931226	-3.8054526	-0.8904149
	H	2.4931226	-3.8054526	0.8904149
	C	-3.5099766	-1.1109136	-2.4322518
	H	-2.8479461	-0.7898524	-3.2353438
	H	-4.3402724	-0.4197278	-2.3122369
	H	-3.8914406	-2.1102241	-2.6557968
	C	-0.593268	3.1660794	2.4125448
	H	0.3134452	3.7675492	2.490953
	H	-0.6696566	2.4797628	3.2512268
	H	-1.4561479	3.8307515	2.3767475
	C	-0.593268	3.1660794	-2.4125448
	H	0.3134452	3.7675492	-2.490953
	H	-1.4561479	3.8307515	-2.3767475
	H	-0.6696566	2.4797628	-3.2512268
	C	-3.5099766	-1.1109136	2.4322518
	H	-2.8479461	-0.7898524	3.2353438
	H	-3.8914406	-2.1102241	2.6557968
	H	-4.3402724	-0.4197278	2.3122369
	O	0.5199028	-2.1266114	0
	C	4.896284	1.1381514	0
	H	5.7890291	0.519171	0
	H	4.8706699	1.7767416	0.8844252
	H	4.8706699	1.7767416	-0.8844252
	C	2.9639859	-3.3851463	0
	H	4.0304645	-3.5950568	0
	H	2.4931226	-3.8054526	-0.8904149
	H	2.4931226	-3.8054526	0.8904149
	C	-3.5099766	-1.1109136	-2.4322518
	H	-2.8479461	-0.7898524	-3.2353438
	H	-4.3402724	-0.4197278	-2.3122369
	H	-3.8914406	-2.1102241	-2.6557968
	C	-0.593268	3.1660794	2.4125448
	H	0.3134452	3.7675492	2.490953
	H	-0.6696566	2.4797628	3.2512268
	H	-1.4561479	3.8307515	2.3767475
	C	-0.593268	3.1660794	-2.4125448
	H	0.3134452	3.7675492	-2.490953
	H	-1.4561479	3.8307515	-2.3767475
	H	-0.6696566	2.4797628	-3.2512268
	C	-3.5099766	-1.1109136	2.4322518
	H	-2.8479461	-0.7898524	3.2353438
	H	-3.8914406	-2.1102241	2.6557968
	H	-4.3402724	-0.4197278	2.3122369
}

mol.update_geometry()
mol.print_out()

set basis cc-pvtz

optimize('b3lyp-d3')

print_variables()

**Comment by jturney** [comment]
I find it troubling that on my computer the nuclear repulsion energy is "inf":

```
Running in c1 symmetry.

  Rotational constants: A =      0.00468  B =      0.00339  C =      0.00276 [cm^-1]
  Rotational constants: A =    140.36411  B =    101.76200  C =     82.71015 [MHz]
  Nuclear repulsion =                  inf
```

Looking at your input I see duplicated atoms. I've modified my local copy of Psi4 to report the duplicated atoms:

```
ERROR: Atom 51 near to atom 26.
ERROR: Atom 52 near to atom 27.
ERROR: Atom 53 near to atom 28.
ERROR: Atom 54 near to atom 29.
ERROR: Atom 55 near to atom 30.
ERROR: Atom 56 near to atom 31.
ERROR: Atom 57 near to atom 32.
ERROR: Atom 58 near to atom 33.
ERROR: Atom 59 near to atom 34.
ERROR: Atom 60 near to atom 35.
ERROR: Atom 61 near to atom 36.
ERROR: Atom 62 near to atom 37.
ERROR: Atom 63 near to atom 38.
ERROR: Atom 64 near to atom 39.
ERROR: Atom 65 near to atom 40.
ERROR: Atom 66 near to atom 41.
ERROR: Atom 67 near to atom 42.
ERROR: Atom 68 near to atom 43.
ERROR: Atom 69 near to atom 44.
ERROR: Atom 70 near to atom 45.
ERROR: Atom 71 near to atom 46.
ERROR: Atom 72 near to atom 47.
ERROR: Atom 73 near to atom 48.
ERROR: Atom 74 near to atom 49.
ERROR: Atom 75 near to atom 50.
```

**Comment by dsirianni** [comment]
Yes, you're correct.  Turns out I made a copy error that added duplicates of lines 26-50 at the end of the file.  Thanks you, sorry for the waste in time.
