### ISSUE TITLE
Trouble getting files copied to CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4public#161]
I'm having trouble getting everything copied into the install location. I generally configure with `mkdir build; cd build; ccmake ..;`, and then customize the CMAKE_INSTALL_PREFIX and other options from the curses gui. I think maybe `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT` doesn't get updated here: https://github.com/psi4/psi4public/blob/master/CMakeLists.txt#L103-L114

What's the purpose of that section explicitly changing the install prefix?

**Comment by loriab** [comment]
Are you building with pcmsolver on? I think @robertodr will have to answer the why in your link. I think most people configure through the setup script, not with cmake directly. With cmake directly and without pcmsolver, https://github.com/psi4/psi4meta/blob/master/conda-recipies/psi4/build.sh has been working.

**Comment by rmcgibbo** [comment]
Hmm, okay. Not building with pcmsolver. I'll trying using the setup script, if that's the standard flow. I did look a lot at your conda recipe, and that's part of what got me confused. I think it has to do with caching of CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT when cmake is configured multiple times, but idk.

**Comment by loriab** [comment]
Ah, the conda recipe may not be catching the problem if involving caching since always invoked fresh. Yes, at least try a ``setup`` configure and look at https://github.com/psi4/psi4public/wiki/8_FAQ_Contents#how-to-see-what-setup-and-cmake-commands-are-active-for-the-object-directory to see if it can help debug your direct cmake build.

**Comment by rmcgibbo** [comment]
Also, if you run `setup`, then `cd obj; make`, but realize something was set wrong (e.g. the path to libpython.so, the cmake variable `PYTHON_LIBRARY`), and then modify within cmake (`ccmake ..` and change a setting, hit `g` to regenerate), the build system doesn't seem to realize that nothing has changed and skip the appropriate stuff. I just did this, and we're rebuilding all the libint files :(

**Comment by loriab** [comment]
That's using `cmake` beyond my experience, as I blow away the objdir if changing cmake variables. @robertodr will have to comment if what you describe is intended behavior. Dial down angular momentum to 4 if you're rebuilding a lot. My thanks to whoever, years ago, fixed the parallel integrals build.

**Comment by rmcgibbo** [comment]
hahah. okay. unfortunately it seems i'm too 'good' at cmake for my own good.

**Comment by rmcgibbo** [comment]
Oh, I see why this happens.
