### ISSUE TITLE
Compiling plugins without source

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4public#162]
Apologies if this is off the development timeline or out of left field. The psi4 plugin system is excellent, and it's one of the really cool unique features of the package.

One way to make it even better would be if it didn't require having access to the source to compile a plugin. Currently, all the static archives stay inside the object directory and are not installed to `prefix`, which means that when the plugins need to link against psi4, they link against the archives in the object directory, and the psi4 binary embeds the location of the source and build directory to use when generating an example plugin makefile. It would be nice to copy the archives to `$PREFIX/lib` instead.

**Comment by loriab** [comment]
That's a good point. I would really like to make it so that one can build a plugin off a conda installation (it's on one of my todo lists). We used to install all the libraries to `$PREFIX/lib`, but I stopped doing that because they weren't doing anything useful. If the mixed gnu-make (of plugins) and cmake and all the compiler/linker flags that must be in sync could be made to work with plugins, we can definitely make appropriate changes to install.

**Comment by jturney** [comment]
I'll check the code usage in the plugin. Currently, plugins only link against the plugin library but it may not be necessary. Everything else is dynamically linked at runtime. If the plugin library isn't needed then none of the archives need to be installed. The headers certainly need to be installed and referenced.

**Comment by jturney** [comment]
All we need for plugins are the headers to create the .so file and the psi4 executable to run against.

**Comment by rmcgibbo** [comment]
Awesome. I'll give this a try soon.

**Comment by rmcgibbo** [comment]
Looks like the includes in the makefile still reference the source directory, and some of the necessary includes, e.g. https://github.com/psi4/psi4public/tree/master/include, aren't copied into the install directory.

**Comment by jturney** [comment]
Ah, ok. I'll fix those...hopefully shortly.

**Comment by rmcgibbo** [comment]
This is a minimal set of missing files, I think:
```
- include/compiler.h
- include/psi4-dec.h
- include/exception.h
- include/process.h
- src/lib/libmints/vector3.i
- src/lib/libparallel/libparallel.h
- src/lib/libchkpt/chkpt.hpp
- src/lib/libchkpt/chkpt.hpp
- objdir/include/psiconfig.h
- objdir/src/lib/libint/libint.h
- objdir/src/lib/libderiv/libderiv.h
```

**Comment by rmcgibbo** [comment]
I'll take a stab at fixing this.

**Comment by loriab** [comment]
I think this was resolved in https://github.com/psi4/psi4public/issues/214
