### ISSUE TITLE
ROHF-CCSD(T) using MP2 Natural orbitals

### ISSUE THREAD

**Issue by ChemTheory** [psi4/psi4public#165]
Dear Psi4 Developers,

I would like to carry out a single point rohf-ccsd(t) calculation on an anion using mp2 natural orbital. Is this calculation possible in psi4?  

Sincerely,
Kaye Archer
Jordan Lab
University of Pittsburgh
Pittsburgh, PA 15260

**Comment by loriab** [comment]
Trying to jump-start the forum, and this topic seemed suitable. Moved to http://forum.psicode.org/t/rohf-ccsd-t-using-mp2-natural-orbitals/51

**Comment by amjames** [comment]
This one was moved to the forum I think we can close it now @loriab
