### ISSUE TITLE
pywrap-freq-e-sowreap

### ISSUE THREAD

**Issue by cdsgroup** [psi4/psi4public#168]
This test is failing for me.  Anybody else have trouble with it?  Lists the displacements and then seems to do nothing.

David

**Comment by loriab** [comment]
I don't find any problems with it when running plain ``ctest -R pywrap-freq-e-sowreap``. But in a larger sense, you're quite right that it's not doing anything. Back in the pre-CMake day, the Makefile took additional steps and actually ran all those displacements https://github.com/psi4/psi4/blob/4.0b5/tests/pywrap-freq-e-sowreap/Makefile.in , then ran https://github.com/psi4/psi4/blob/master/tests/pywrap-freq-e-sowreap/tests so as to make a proper test case. This multi-psi4 invokation hasn't yet been ported to the CMake/CTest system. So it's good that this is a ticket.

**Comment by amjames** [comment]
@loriab 
I have (almost) worked out a fix for this. 

Would anyone  be opposed to a helper script that goes in an runs the generated `FREQ-x.in` files, appends the tests to `FREQ-master.in` and runs it as well? It will work similarly to `runtest.py` so it will record the outcome in `testresults.log` as well, and is general so could be a solution for multi-invocation tests going forward. 

If so I just need hook this in with CMake/CTest and I can open a PR. 

Also, can anyone confirm that the testing reference values in [tests](https://github.com/psi4/psi4/blob/master/tests/pywrap-freq-e-sowreap/tests) are okay?

**Comment by loriab** [comment]
A solution for multi-invocation tests going forward would be much appreciated. We used to incorporate this into the Makefile build system (https://github.com/psi4/psi4/blob/4.0b5/tests/pywrap-freq-e-sowreap/Makefile.in), but I never got around to converting it for CMake.

I modified the old script (below) and checked the tests file, and it still looks ok.

```bash
>>> psi4/tests/pywrap-freq-e-sowreap: bash script.sh 
Performing finite difference calculations by energies
 13 displacements needed.
Performing finite difference calculations by energies
 13 displacements needed.
 Computation complete.
	Frequencies.......................................................PASSED
	ZPVE..............................................................PASSED
	SP energy.........................................................PASSED
	SP NRE............................................................PASSED
	SP NRE............................................................PASSED
	SP NRE............................................................PASSED
>>> psi4/tests/pywrap-freq-e-sowreap: cat script.sh 
PSIDATADIR=../../lib

../../objdir2/bin/psi4 -p     PSIDATADIR input.dat 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-1.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-2.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-3.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-4.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-5.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-6.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-7.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-8.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-9.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-10.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-11.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-12.in 
../../objdir2/bin/psi4 -p     PSIDATADIR FREQ-13.in 
/bin/cat tests >> FREQ-master.in
../../objdir2/bin/psi4 -p PSIDATADIR FREQ-master.in 
```
