### ISSUE TITLE
Input broken?

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4public#169]
The following input file fails with the following message:

```
Traceback (most recent call last):
  File "/Users/francesco/Source/psi4/lib/python/inputparser.py", line 732, in process_input
    temp = re.sub('^from __future__ import .*$', future_replace, temp, flags=re.MULTILINE)
TypeError: sub() got an unexpected keyword argument 'flags'
```

I was wondering: is it possible that recent changes to python affect the ability to read user-defined basis sets from input files?

```
molecule h2o {
0 1
O
H 1 1.0
H 1 1.0 2 104.5
}

basis {
cartesian
H 0
S 3 1.00
      3.42525091 0.15432897
      0.62391373 0.53532814
      0.16885540 0.44463454
****
O 0
S 3 1.00
    130.7093200 0.15432897
     23.8088610 0.53532814
      6.4436083 0.44463454
SP 3 1.00
      5.0331513 -0.09996723 0.15591627
      1.1695961 0.39951283 0.60768372
      0.3803890 0.70011547 0.39195739
****
}

energy('scf')
```

**Comment by jturney** [comment]
Hmmm, which version of Python are you using?

**Comment by fevangelista** [comment]
Default on a Mac, 2.7.3 I guess.

Francesco

On Aug 18, 2015, at 5:59 PM, Justin Turney <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm, which version of Python are you using?

-
Reply to this email directly or view it on GitHub<https://github.com/psi4/psi4public/issues/169#issuecomment-132368503>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by fevangelista** [comment]
Actually, I think this might be a bigger problem.  I was able to fix the issue with 'flags' by replacing some code in /lib/python/inputparser.py

```
    future_re = re.compile('^from __future__ import .*$',flags=re.MULTILINE)
    temp = future_re.sub(future_replace, temp)
    #temp = re.sub('^from __future__ import .*$', future_replace, temp, flags=re.MULTILINE)
```

but then I get this other error message (even with the newest commit):

```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/Users/francesco/Source/psi4/lib/python/aliases.py", line 39, in <module>
    from wrappers import *
  File "/Users/francesco/Source/psi4/lib/python/wrappers.py", line 39, in <module>
    from driver import *
  File "/Users/francesco/Source/psi4/lib/python/driver.py", line 38, in <module>
    from interface_cfour import *
  File "/Users/francesco/Source/psi4/lib/python/interface_cfour.py", line 40, in <module>
    import qcdb
  File "/Users/francesco/Source/psi4/lib/python/qcdb/__init__.py", line 35, in <module>
    from .molecule import Molecule
  File "/Users/francesco/Source/psi4/lib/python/qcdb/molecule.py", line 39, in <module>
    from .libmintsmolecule import *
  File "/Users/francesco/Source/psi4/lib/python/qcdb/libmintsmolecule.py", line 31, in <module>
    from oldpymodules import OrderedDict
ImportError: No module named oldpymodules
```

**Comment by loriab** [comment]
I suspect this has to do with the python3 fixes. Will take a look tomorrow.

**Comment by rmcgibbo** [comment]
I think this must be python2.6. I tested `re.sub` in 2.7.10 and 2.6.9, and `re.sub` takes `flags` just fine as a kwarg in 2.7.10, but not in 2.6.9.

**Comment by rmcgibbo** [comment]
`ImportError: No module named oldpymodules`. yeah, this is py26. the code is missing a leading `.` for absolute import. my fault.

**Comment by fevangelista** [comment]
Thanks for the fix.
