### ISSUE TITLE
Psi4 does not call LibERD 

### ISSUE THREAD

**Issue by keipertk** [psi4/psi4public#171]
I am interfacing LibERD with GAMESS and would like to use the Psi4 interface as a reference. Psi4 does not call LibERD, even when compiled with it. This issue has been confirmed via email by @ryanmrichard.

I first invoke:
setup --erd on --fc gfortran --type debug
and install normally, verifying that DENABLE_LIBERD is set for CMake.

Then I tried debugging and setting a breakpoint at the ERD entry point, erd__gener_eri_batch. I tried a variety of sample input files, and that function is never reached. Next, I went to the ERD wrapper code at ./psi4public/src/lib/libmints/erd_eri.cc and enabled the DEBUG preprocessor macro which adds print statements for ERD parameters. The print statements are not printed, even if I remove the IF statements.

Third, I figured LibInt might be called instead of ERD, so I recompiled with --max-am-eri 0 in an attempt to disable LibInt. There was no change in the behavior of the code.

**Comment by jturney** [comment]
Try setting the option `INTEGRAL_PACKAGE = ERD` in your input file. Let me know if that works.

**Comment by keipertk** [comment]
That did not change the behavior. I noticed that INTEGRAL_PACKAGE is printed for the dfccd1 test (and others) and lists INTEGRAL_PACKAGE = ERD as expected, even without specifying that in the input file.

**Comment by ryanmrichard** [comment]
I also experienced no change by trying that.  Watching the build logs I noticed both ERD and LibInt are built.  I do not recall this being the default behavior when I was using ERD about a year ago.  Is it possible some of the CMake infrastructure changes caused this?

**Comment by jturney** [comment]
Ah, ok. I think I see the problem in the code. Patch coming shortly.

**Comment by jturney** [comment]
Try pulling and testing now. I am unable to test it on my box.

**Comment by keipertk** [comment]
That fixed it! Thank you very much for the help.
