### ISSUE TITLE
Geometry optimization failures

### ISSUE THREAD

**Issue by leeping** [psi4/psi4public#18]
Dear devs,

I've been running some dihedral-constrained optimizations on capped dipeptides, and a small percentage of them fail.  Examples are attached.

In the first example, the optimizer takes a huge step and ends up in a crazy geometry.  I worked around it by setting ```intrafrag_step_limit     0.1```.  Unfortunately I lost the .intco file, but the output file shows that two dihedrals have been constrained.

https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize.dat
https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize.out
https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize.xyz

In the second example, the energy oscillates with periodicity 3.  

https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize-1.dat
https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize-1.out
https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize-1.xyz
https://dl.dropboxusercontent.com/u/5381783/psi4-opt/optimize-1.THR.intco

I'll try to work around this by using ```step_type nr```, but thought it was worth reporting nonetheless.

Thanks,

- Lee-Ping Wang (Postdoc, Stanford)

**Comment by loriab** [comment]
Reasonably, since this is more than 2 years old, you've deleted the dropbox files. Maybe @psi-rking has the inputs to test if any of the newfangled optimization modes work on these cases. Thanks for reporting, but I'm closing since we probably don't have the info to reconstruct the problem.
