### ISSUE TITLE
Increase maximum angular momentum

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4public#180]
Hi,

from what I gather in the libint routines, the maximum angular momentum supported by psi4 seems to be G functions (l=4).

Do you have any plans to get rid of this limitation?

cc-pV6Z has up to I functions (l=6), and ideally one would like to run forces (and semi-numerical Hessians), which means that the program should support integrals over l=7 functions.

**Comment by susilehtola** [comment]
On another issue, the buildtime configuration now seems to ask for LIBINT_OPT_AM, which AFAIK is the maximum angular momentum for which specially optimized code is generated.

It doesn't ask a value for LIBINT_MAX_AM at all, which determines the maximum angular momentum for which evaluation routines are generated.

In Ed's upstream release of libint,  LIBINT_OPT_AM defaults to (LIBINT_MAX_AM/2 + 1).

I believe the scripts should be adjusted to make it possible to set OPT_AM and MAX_AM separately, since a large value of OPT_AM generates huge code.

**Comment by susilehtola** [comment]
I've linked the Fedora package to a separately compiled libint package (also in the official Fedora repository) for which LIBINT_MAX_AM = 11, LIBINT_OPT_AM = 7, and it would seem that at least MP2 geometry optimization works with cc-pV6Z.

**Comment by kannon92** [comment]
I am not really sure about all the LIBINT commands as I try to avoid dealing with the integral routines.  I typically just pass a --max-am-eri=7 to my setup script so I can compile with higher angular momentum.

**Comment by Konjkov** [comment]
Yes, kannon92 that is what is written in the docs:
https://github.com/psi4/psi4public/wiki/2_Planning#setupmaxameri

**Comment by susilehtola** [comment]
The documentation is rather confusing, since there's no way one wants to compile with OPT_AM high enough to get derivatives of I functions necessary for cc-pV6Z forces, but this is exactly what the cmake script looks like it's doing... Instead, one should be able to define MAX_AM and OPT_AM separately, like they're done in upstream libint.
