### ISSUE TITLE
mcscf

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4public#182]
Dear all, 

Can someone please provide a simple input file for a state averaged mcscf calculation for excited states : nroots= 3 ?

**Comment by mbanck** [comment]
The casscf-sa-sp test case sounds like something similar to what you want? I am not sure you can really specify each CSF in PSI4, as e.g. with the "ref" card in MOLPRO, but I have to admit I am no expert on PSI4, just trying to help here.

**Comment by dgasmith** [comment]
@lucamontana Did mbanck's answer work for you or are you looking for something else?
