### ISSUE TITLE
Compiling Psi4 in Mac: git_update problem

### ISSUE THREAD

**Issue by anpicon** [psi4/psi4public#183]
Compiling Psi4 I got this error:
.
.
.
[ 60%] Building CXX object src/lib/libchkpt/CMakeFiles/chkpt.dir/nao.cc.o
[ 60%] Building CXX object src/lib/libchkpt/CMakeFiles/chkpt.dir/am2canon_shell_order.cc.o
[ 60%] Linking CXX static library ../../../lib/libchkpt.a
[ 60%] Built target chkpt
Scanning dependencies of target cubeprop
[ 60%] Building CXX object src/lib/libcubeprop/CMakeFiles/cubeprop.dir/csg.cc.o
[ 60%] Building CXX object src/lib/libcubeprop/CMakeFiles/cubeprop.dir/cubeprop.cc.o
[ 60%] Linking CXX static library ../../../lib/libcubeprop.a
[ 60%] Built target cubeprop
Scanning dependencies of target git_update
fatal: Not a git repository (or any of the parent directories): .git
make[2]: *** [src/lib/libpsipcm/CMakeFiles/git_update] Error 128
make[1]: *** [src/lib/libpsipcm/CMakeFiles/git_update.dir/all] Error 2
make: *** [all] Error 2

-----------------------
The git and cmake version from macports is 2.5.3 and 3.3.3 respectively. I used the setup command:
./setup --plugins --fc gfortran-mp-4.8  --accelerate objdir

I was wondering if you can provide me some input to solve the problem. Thank you.

**Comment by ryanmrichard** [comment]
The actual error is somewhere in the ellipses, so we will need more info.  The fact that make is reporting that the error occurred in `src/lib/libpsipcm` suggests to me that it may be a problem with finding the PCM repo on GitHub, but I need more info to be sure.  Can you run:
```
export VERBOSE=1
```
(in Bash) or:
```
setenv VERBOSE 1
```
(in TCSH)? 
Rerun the build command and then post the full output here.  If you are curious, `VERBOSE` is the environment variable that tells CMake to spit out more information.
