### ISSUE TITLE
Incorrect gradients with an external potential

### ISSUE THREAD

**Issue by kratman** [psi4/psi4public#184]
The PSI4 (0.3.183, 5427c0a) gradient routine does not seem to be giving the correct values when an external field is defined using the QMMM module.

I attached two test calculations:
1) A water dimer with 1 water QM and the second represented as point charges
```
memory 1 gb
set reference rks
set basis 6-31++G**
set guess sad
set scf_type df

molecule QMregion {
  0 1
  O  -0.778803000000  0.000000000000  1.132683000000
  H  -0.666682000000  0.764099000000  1.706291000000
  H  -0.666682000000  -0.764099000000  1.706290000000
  symmetry c1
  no_reorient
  no_com
}

gradient("PBE0")

Chrgfield = QMMM()
Chrgfield.extern.addCharge(-0.834,1.649232019048,0.0,-2.356023604706)
Chrgfield.extern.addCharge(0.417,0.544757019107,0.0,-3.799961446760)
Chrgfield.extern.addCharge(0.417,0.544757019107,0.0,-0.912085762652)
psi4.set_global_option_python('EXTERN',Chrgfield.extern)

gradient("PBE0")
```
2) A helium atom with a point charge (q=-1) 1 Angstrom away
```
memory 1 gb
set reference rks
set basis 6-31G*
set guess sad
set scf_type df

molecule QMregion {
  0 1
  He 0.0  0.0  0.0
  symmetry c1
  no_reorient
  no_com
}

gradient("PBE0")

Chrgfield = QMMM()
Chrgfield.extern.addCharge(-1,0.0,0.0,1.8897261245650618)
psi4.set_global_option_python('EXTERN',Chrgfield.extern)

gradient("PBE0")
```

For test 1, the gradient from the water and the water+charges are different, but they do not agree with the forces returned by an equivalent calculation with Gaussian. The isolated water molecule has gradients that agree with the Gaussian forces, but once the charges are added the Gaussian and PSI4 calculations return different results.

For test 2, the PSI4 gradient is zero for the for the helium with and without the point charge. The charge has no effect on the results. When I repeated the calculation with Gaussian, there was a finite force on the helium atom when a charge was included.

Here are the gradient results I pulled from the output files:
```
Water+Charges (TIP3P charges: O->-0.834, H->0.417)

PSI4 gradient without charges:
       1       -0.000345685156    -0.000000503248    -0.001768512746
       2        0.000171019827     0.000099064969     0.000874930893
       3        0.000170945942    -0.000098562011     0.000874553581

Gaussian forces without charges:
      1        8           0.000342119    0.000000502    0.001755656
      2        1          -0.000171096   -0.000103970   -0.000878017
      3        1          -0.000171022    0.000103468   -0.000877640

PSI4 gradient with charges:
       1        0.001872262723    -0.000000506498    -0.002344911788
       2       -0.000937982580    -0.003306842432     0.001163140925
       3       -0.000938055973     0.003307348640     0.001162761678

Gaussian forces with charges:
      1        8           0.002079660    0.000000498   -0.002984605
      2        1           0.000413259    0.000612887   -0.001458686
      3        1           0.000413331   -0.000613388   -0.001458305

--------------------------------------------------------------------
He+Charge (q = -1.0, r = 1.0 Ang.)

PSI4 gradient without charges:
       1        0.000000000000     0.000000000000     0.000000000000

Gaussian forces without charges:
      1        2           0.000000000    0.000000000    0.000000000

PSI4 gradient with charges:
       1        0.000000000000     0.000000000000     0.000000000000

Gaussian forces with charges:
      1        2           0.000000000    0.000000000    0.038125930
```

Please let me know if you need more information or if I have a mistake in my input scripts.

**Comment by andysim** [comment]
Thanks for the detailed bug report.  I suspect that the gradients for the external perturbation are not being computed, but that should be quite easy to fix.  I will hopefully have some time to look into it later this week, or early next week.

Andy.

**Comment by andysim** [comment]
Ok, thanks to your very detailed examples, I was able to track down the problem(s).  If you pull the latest version of the code, it should be fixed.  There's a new test case, extern1, that confirms the correctness of the gradients by finite differences.

The PBE results don't seem to match the Gaussian results that you posted; I don't have access to Gaussian so I can't investigate that any further, I'm afraid.  A good place to start would be an SCF calculation, because DFT grids are not uniform between packages.  It's also a good idea to manually specify the basis set (Psi4 uses the G94 standard) to ensure that both packages are using the exact same functions.  With these changes, the energies and gradients should match exactly; if not it's probably confusion between A/Bohr in the Gaussian input for the TIP3P fragment.  Until these fixes, Psi4 assumed that the external potential was always in Bohr, but now the code will assume the same units as those used to specify the QM molecule.

Good luck!

Andy.

**Comment by kratman** [comment]
Thank you for fixing the gradient routines. Having PSI4 gradients will be really helpful.

I am calling PSI4 in my QMMM calculations, so I will run through some of my pre-made test cases and look at extern1 to confirm that I am doing everything correctly.

Thanks,
-kratz

**Comment by susilehtola** [comment]
Oh, and if you manually specify the basis set, be sure to turn off basis set rotations in Gaussian; otherwise the basis sets won't match.

**Comment by susilehtola** [comment]
The magic keyword is IOp(3/60=-1).

**Comment by kratman** [comment]
I checked the gradients with my pre-made tests and everything seems to be working properly. Thanks.
