### ISSUE TITLE
OMP2 didn't use symmetry in SCF calculation but OMP3/OCEPA does

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4public#186]
Hi, PSI4 users.
I run OMP2/OMP3/OCEPA for cubane molecule (Molecular point group: d2h, Full point group: Oh).
And found that OMP2 didn't use symmetry in SCF run, but OMP3/OCEPA does.
Using symmetry significantly accelerates calculation. 

My input:
>#
>memory 1000 mb
>molecule cubane {
>0 1
> H       1.4194     -1.4194      1.4194
> C       0.7855     -0.7855      0.7855
> H       1.4194     -1.4194     -1.4194
> C       0.7855     -0.7855     -0.7855
> H       1.4194      1.4194      1.4194
> C       0.7855      0.7855      0.7855
> H       1.4194      1.4194     -1.4194
> C       0.7855      0.7855     -0.7855
> H      -1.4194      1.4194     -1.4194
> C      -0.7855      0.7855     -0.7855
> H      -1.4194      1.4194      1.4194
> C      -0.7855      0.7855      0.7855
> H      -1.4194     -1.4194      1.4194
> C      -0.7855     -0.7855      0.7855
> H      -1.4194     -1.4194     -1.4194
> C      -0.7855     -0.7855     -0.7855
>}
>
>set {
>  basis cc-pVDZ
>  scf_type pk
>  E_CONVERGENCE 10
>  D_CONVERGENCE 10
>  molden_write true
>}
>
>energy('omp2')

Git: Rev {master} 521f06adb441ac1e2f1732eb1cd090190b409c49

Vladimir

**Comment by bozkaya** [comment]
Dear Vladimir,

We have two kind of orbital-optimized (OO) methods now. The old codes are using conventional integrals and they can be called by energy('conv-omp2'), energy('omp3'), energy('omp2.5'), and energy('ocepa). All these methods are available in the OCC module and all methods of the OCC module take advantages of real Abelian point group symmetry.

Recently,  I have introduced a new module for OO methods as well as standard MP and CC methods, which is called as DFOCC module. In DFOCC module, we have density-fitting and Cholesky decomposition approximations for molecular integrals. Hence, the OO methods of DFOCC module are  df-omp2, cd-omp2, df-omp3, cd-omp3, df-omp2.5, and cd-omp2.5. Df/cd-ocepa methods are coming soon. These methods can be called by energy('df-omp2'), energy('df-omp3'), energy('df-omp2.5'), and cd versions can be run similarly. All methods of DFOCC module has energy and gradients (RHF and UHF).  Please note that when you asked df and cd methods you should set "scf_type df" and "scf_type cd", respectively. Further, DFOCC module does NOT use the molecular symmetry. All DFOCC methods are greatly faster than their conventional counterparts. For a discussion of timing for OMP2, OO-RI-MP2 of orca, and our new DF/CD-OMP2 you may want to read our recent paper, J. Chem. Theory Comput., 2014, 10 (6), pp 2371–2378 (DOI:10.1021/ct500231c). Finally, please note when you set energy('omp2') the df-omp2 code runs, for old code you should use energy('conv-omp2'). For more details please refer to our manual section OCC/DFOCC. 

As a conclusion, do not worry about the symmetry if your main concern is the efficiency . The present DF/CD-OO methods are greatly faster than the conventional OO methods.

Best regards,
Ugur Bozkaya

**Comment by Konjkov** [comment]
I'm sorry Ugur but may be you don't quite understand me.
SCF run (before OCC optimization) didn't use symmetry in DF-OMP2 case, but in DF-OMP2/CEPA does. It looks pretty strange to me, because I do not see any connection between the use of symmetry in the preliminary SCF calculation and subsequent OO-CC.
Vladimir.

**Comment by Konjkov** [comment]
thenks for precise explanation
