### ISSUE TITLE
bin and tools folders in repo

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#187]
I didn't recognize the contents of the bin folder in the repo (https://github.com/psi4/psi4public/tree/master/bin) and the last changed dates are from 2–8 years ago. The build system has changed a lot since then. Can anyone who recognizes these files comment on if they're still useful?

Regarding the tools folder in the repo (https://github.com/psi4/psi4public/tree/master/tools), I do remember many of the contents from the 2014 developers' meeting. Some of the CMake strategies, such as globbing, have changed since then. @robertodr or anyone else, could you take a look and see if anything is out-of-date or better off residing in psi4/psi4meta or lib/scripts or if these scripts should stay as they are?

**Comment by jturney** [comment]
All but two of the files in ```bin``` are specific to the old configure.ac build system.  The other two: ```psi4-config.in``` I do not think it is used and is a left over of the old plugin system and ```git_list_authors.sh``` was just a toy script that someone put in.  The files in ```bin``` should be safe to remove.

**Comment by loriab** [comment]
bin contents removed by 63463153e64c41809e636aa41bc56e6cfd765238. Will close this after tools sorted out.

**Comment by robertodr** [comment]
`tools` contains the stuff needed for the lines-of-code bar charts generator. It can be removed but all `CMakeLists.txt` in the leaf directories will then need a clean up. Same goes for the `make_cmake_files.py` script. I can take care of this, just let me know if you're OK with the bar charts generator to be removed.

**Comment by loriab** [comment]
I don't use the bar charts, but I've no objection to them being in the code so long as you or others find them useful. I just wanted to check if any of ``tools/*`` was old and disused.

**Comment by robertodr** [comment]
It's not really used, so if nobody else objects I'll remove it. There might be a way to restructure it so that it can live apart from the code in `psi4meta`...

**Comment by loriab** [comment]
Ok, whichever you think best. And sure, try for a connection with ``psi4meta``. If you have a script to run that produces some sort of reporting webpage, psinet can run it and put the results on psicode.org, I'd think.

**Comment by loriab** [comment]
Closed by  https://github.com/psi4/psi4/pull/113
