### ISSUE TITLE
dfomp test cases failing

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#190]
Several dfocc test cases have failed since the summer when we cleared out most of them. Namely, dfomp2p5-grad1, dfomp3-grad2, dfomp2p5-2, and dfomp3-2. Seems to happend on multiple machines: https://testboard.org/cdash/testSummary.php?project=3&name=dfomp2p5-2&date=2015-11-17. @bozkaya, could you take a look? Thanks.

**Comment by jgonthier** [comment]
I can confirm these test cases fail on my machine with a psi4public pull from yesterday (OpenSuse 13.2, gcc 4.8.3)

**Comment by bozkaya** [comment]
All these tests are successful on my mac, which not the current version of psi4. Then, I download the latest psi4 binary on my linux cluster, then dfomp2p5-grad1 is still successful. However, dfomp3-grad2 fails. When trace the error, I saw that the SCF energies are quite different. Hence, there should be some changes in the SCF module recently. Now, I am compiling the current version of psi4, and I will update the tests that you were mentioned. 

I can attribute the failure of all tests whose name ended with "2", which means they are open-shell molecules. However, dfomp2p5-grad1 should be successful.

**Comment by loriab** [comment]
As of this morning, I show dfomp3-2 and dfomp2p5-2 as fixed and dfomp2p5-grad1 and dfomp3-grad2 as still broken. You can see the errors by clicking on the "Failed" link at https://testboard.org/cdash/viewTest.php?onlyfailed&buildid=44226.

**Comment by bozkaya** [comment]
Hi Lori,

I can not reproduce failings on my computers. Could you send me output files for the failed tests so that I see what is gong wrong?

**Comment by loriab** [comment]
Sure, here they are.

**Comment by loriab** [comment]
[ugur_dfomp3-grad2.txt](https://github.com/psi4/psi4public/files/38255/ugur_dfomp3-grad2.txt)
[ugur_dfomp2p5-grad1.txt](https://github.com/psi4/psi4public/files/38256/ugur_dfomp2p5-grad1.txt)

**Comment by bozkaya** [comment]
Hi Lori,

I have just checked your output file for dfomp2p5-grad1. However, your input file is wrong. Please compare it with the following, which is the one in the public repo:

#! DF-OMP2.5 cc-pVDZ gradients for the H2O molecule.

ref_vals = [                                                             #TEST
             [ 0.000000000000,     0.00000000000000,     0.01227994599573],  #TEST
             [ 0.000000000000,     0.00200475312336,    -0.00613997299786],  #TEST
             [ 0.000000000000,    -0.00200475312336,    -0.00613997299786]   #TEST
           ]                                                             #TEST
ref = psi4.Matrix(3, 3)                                                #TEST
ref.set(ref_vals)

memory 256 mb

molecule h2o {
0 1
o
h 1 0.958
h 1 0.958 2 104.4776
}

set {
  basis cc-pvdz
  df_basis_scf cc-pvdz-jkfit
  df_basis_cc cc-pvdz-ri
  scf_type df
  guess sad
  freeze_core true
}
gradient('df-omp2.5')

grad = psi4.wavefunction().gradient()                           #TEST
compare_matrices(ref, grad, 5, "Analytic gradients")              #TEST

**Comment by bozkaya** [comment]
Hi Lori,

dfomp2p5-grad2 and df-omp3-grad2 tests were failing due to wrong scf solutions. Both are fixed now. 

Best regards,
Ugur.

**Comment by loriab** [comment]
Found it– both your dfomp2-grad1 and -grad2 were both registered with name grad1, so CTest was confused. Fixed with 9c19af629e69161a95eabbbaa737b791c1ce1874

**Comment by loriab** [comment]
Last two pass now (https://testboard.org/cdash/viewTest.php?onlydelta&buildid=44436), so item complete.
