### ISSUE TITLE
2 electron integrals

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4public#194]
Dear all, 

Does any one know why psi4 performs a 2 electron integral calculation just before dmrg calculation starts, although one has activated density fitting keyword ?

Bests
Luca

**Comment by loriab** [comment]
I can't say exactly, but we usually put in that flag if the scf has been done DF, but the subsequent post-SCF needs for 2e- integrals.

**Comment by CDSherrill** [comment]
Yes, most likely the DMRG code is not adapted to use density fitting, so it
has to go off and compute all the usual 2-electron integrals before it
starts up.

**Comment by lucamontana** [comment]
It makes me sad to hear this but any way it is how it is.
Thanks a lot for the rapid responses.

Best wishes
Luca

**Comment by CDSherrill** [comment]
Well, no reason to be sad, the integrals computation is very fast compared
to a DMRG computation, so the fact that the integrals are recomputed is
really not a big deal.

David

**Comment by lucamontana** [comment]
Unfortunately integral computation is not parallelized, 
and my molecule is rather large  (300 atoms).

**Comment by ryanmrichard** [comment]
We have added this to our feature request list.
