### ISSUE TITLE
PCM-UHF fails to converge

### ISSUE THREAD

**Issue by vymetal** [psi4/psi4public#198]
Dear developers,

I am interested in wave functions and electron densities of molecules solvated by PCM. However, the current implementation of PCM in PSI4 (Psi4 0.3.131 Driver, Git: Rev {master} 7a8bad0 dirty) provides inconsistent electronic properties (e.g. dipole moment) for restricted and unrestricted HF/DFT methods. Obviously, both approaches should converge to the same values for the closed shell systems, but in both cases, the final wave functions and density matrices are perhaps wrong. Dipole moments calculated by electric field perturbation method differ from dipoles calculated from SCF density matrices. It can be illustrated by running the attached input.
[input.txt](https://github.com/psi4/psi4public/files/72199/input.txt)

I am not expert in PCM methods or in the QM codes, but I suspect  this piece of code in hf.cc:
```
   540  #ifdef HAVE_PCMSOLVER
   541          if(pcm_enabled_) {
   542              // Prepare the density
   543              SharedMatrix D_pcm;
   544              if(same_a_b_orbs()) {
   545                D_pcm = Da_;
   546                D_pcm->scale(2.0); // PSI4's density doesn't include the occupation
   547              }
   548              else {
   549                D_pcm = Da_;
   550                D_pcm->add(Db_);
   551              }
   552  
   553              // Add the PCM potential to the Fock matrix
   554              SharedMatrix V_pcm;
   555              V_pcm = hf_pcm_->compute_V();
   556              if(same_a_b_orbs()) Fa_->add(V_pcm);
   557              else {
   558                Fa_->add(V_pcm);
   559                Fb_->add(V_pcm);
   560              }
   561          }
   562  #endif
```
If these lines are disabled, the dipole moments calculated from density matrices agree with those from finite electric field perturbation calculations. Moreover, convergence for restricted and unrestricted HF/DFT is restored, but the polarization energy and total energy reported by psi4 is not affected. Perhaps some double-counting of PCM contributions takes place in the code. I would be very grateful if this part of the code is reviewed by developers.

Regards,

Jiri Vymetal

**Comment by robertodr** [comment]
@vymetal I am working on this issue and will respond ASAP. The code you highlighted takes care of adding the PCM potential to the Fock matrix. Commenting it out will run a calculation _in vacuo_ and I guess that's not what you want.

**Comment by robertodr** [comment]
@vymetal commit df548db seems to fix both the problems you reported, i.e. convergence failures for PCM-UHF and the discrepancies in calculated first-order properties *wrt* finite difference calculations.
The input file you provided is now a test case for first-order properties with PCM (it's in `tests/pcm_dipole`) In case your problems persist, don't hesitate to open a new issue.
