### ISSUE TITLE
Compilation error (missing PsiAPI)

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4public#205]
Commit e6916b7b14ee873e1218de36bab6fb60e99abf3d gives a compilation error.  The PsiAPI directory is missing:

```
CMake Error at CMakeLists.txt:286 (add_subdirectory):
  add_subdirectory given source "PsiAPI" which is not an existing directory.
```

This should be an easy fix.

**Comment by ryanmrichard** [comment]
Sorry, missed a file.  See if it works now...

**Comment by fevangelista** [comment]
No problem.  It's now working.
