### ISSUE TITLE
ROHF energy inconsistency

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4public#210]
Running version 0.3, I see

SCF Energy (ref):             -1.4267662531
Nuclear repulsion energy:      1.1382844453
One-electron energy:          -2.8081568717
Two-electron energy:           0.5202338704
Dropped core energy:           0.0000000000
Total electronic energy:      -2.2879230012
Total SCF energy:             -1.1496385559

*** Calculated Energy Differs from SCF Energy in CHKPT ! ***

input.dat as follows

molecule {
0 2
H        0.000000    0.889899    0.000000
H        0.889899    0.000000    0.000000
H        0.000000   -0.889899    0.000000
}

set basis STO-3G
set reference rohf
set NUM_ROOTS 3
energy('fci')

**Comment by dgasmith** [comment]
Hello,
The CI code has received a significant overhaul recently. Can you please recompile a new version of psi4 from a fresh git pull and try again?

**Comment by dgasmith** [comment]
I see no issues on master. Closing.

**Comment by susilehtola** [comment]
Yeah this seems to have been fixed.
