### ISSUE TITLE
install headers properly

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#215]
See conversation at https://github.com/psi4/psi4public/issues/214 . We need to copy the main psi4/include headers at install-time. Also, consider if all headers (incl. the `src/lib-bin/*/*.h` that _are_ currently getting installed) should properly be behind a `include/psi4` or `include/psi` namespace.

**Comment by robertodr** [comment]
@loriab the `install(FILES "${headers_list} include/lib*)` directives are everywhere in all subdirectories in `src/lib-bin` since we are using the `make_cmake_files.py` script to generate the leaf `CMakeLists.txt`. Most of them are most likely not needed in a proper installation.
Possibly the include directory layout in robertodr/psi4public@d5a193f1 is good enough?

**Comment by loriab** [comment]
@robertodr's PR fixes the urgent problem. @jturney, @CDSherrill, @lothian: is there any support for namespacing the includes (e.g., in the conda package, python, chemps, psi4, hdf5, possibly gcc headers are all installed to `prefix/include`). If anyone thinks this isn't a problem, just close the ticket.

**Comment by jturney** [comment]
Didn't we use to install the psi4 headers into ```prefix/include/psi4``` ?

**Comment by CDSherrill** [comment]
I think that sounds right, Jet.

David

**Comment by loriab** [comment]
Just checked back to c. 2010– they've always gone directly into `prefix/include`

**Comment by jturney** [comment]
Oh, you're right....I'd prefer everything goes into ```prefix/include/psi4```.  

Also, we put the basis sets and other files into ```prefix/share/psi``` should that be changed to ```psi4```?

**Comment by loriab** [comment]
I, too, support the namespace. Yes, they should probably be consistent. `psi4` would be nice, but I'm not wholly against `psi` for consistency. Basically, I think the Debian packagers are going to insist on various small changes like these, and I'd like to anticipate them. It seems importing https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html is how one does this properly.

**Comment by jturney** [comment]
I'd be for using ```psi4``` since psi3 is still out in the wild and uses ```psi```.

Looking at that cmake url it looks like only ```DOCDIR``` is automatically namespaced. We'd only need to namespace ```INCLUDEDIR``` and ```DATADIR```.

Maybe now is a good time to rename the ```lib``` in our top source directory to ```share/psi4``` since that is where the items will be installed.

**Comment by loriab** [comment]
Installed changes:
* `prefix/include/herebeheaders.h` --> `prefix/include/psi4/herebeheaders.h`
* `share/psi/python` --> `share/psi4/python`, etc.

Then, Jet, you're also proposing the following?
Source changes:
* `top-source-dir/lib/python` --> `top-source-dir/share/psi4/python`

I agree the `lib` is misleading, but two directory levels is a lot just to match names. I'd leave it as is or move to `share`. That won't affect the public interface, so easier to change in future.

**Comment by jturney** [comment]
I think we're on the same page (certainly for the headers).

Installed changes:
* agreed
* ```share/psi/* --> share/psi4/*```

Source changes:
* ```top-source-dir/lib/* --> top-source-dir/share/psi4/*```

I'd like to have the two directory levels to keep the source and install tree similar could keep confusion down when setting ```PSIDATADIR```.

**Comment by loriab** [comment]
Installed changes:
* agreed
* agreed (yes, that's what I meant to write)

Source changes:
The extra psi4 dir in source wouldn't be expected in includes (i.e., we're not moving `top-source-dir/include/` to `top-source-dir/include/psi4` so I don't see that the shareables folder in source needs the namespace protection either. And setting `PSIDATADIR` is a slightly advanced topic. If the concensus is for mirroring the dir structure of shareables, I'm fine with it, but I mildly favor as is or `share`.

**Comment by jturney** [comment]
I'm OK with just making the change in the source since as you said we're not changing include.

* ```top-source-dir/lib/* --> top-source-dir/share/*```

**Comment by loriab** [comment]
Ok, the task of this ticket shall be:

Install changes:
* `prefix/include/*` --> `prefix/include/psi4/*`
* `share/psi/*` --> `share/psi4/*`

Source changes:
* `top-source-dir/lib/*` --> `top-source-dir/share/*`

with reference to https://github.com/SebWouters/CheMPS2/blob/master/CMakeLists.txt as needed, since CheMPS2 has already been through packaging.

**Comment by loriab** [comment]
Above commit addresses the first two bullets. Third bullet needs to be coordinated with merge to branch `wavefunction_pass`.
