### ISSUE TITLE
-jN builds failing

### ISSUE THREAD

**Issue by lothian** [psi4/psi4public#219]
It appears that -jN compilations – I typically build with -j4 – are failing because of incorrect blocking of dependencies.  In at least one case, the build reaches libmints before libint is complete, resulting in a missing libint.h header file.  When I compile serially, everything runs smoothly.  However, it's not clear to me what has changed in the compilation infrastructure in the last day or so to cause this problem.

**Comment by robertodr** [comment]
Could you copy-paste the error you get from the `-jN` build? It might be the same problem I hit on some nightly builds on stallo and that I have never been able to reproduce.

**Comment by lothian** [comment]
Actually, for the build I just tried, the real source of the error was in libdpd, which now includes libmints/mints.h, which includes (through basisset.h) libint.h.  Since the libdpd/Makefiles.txt did not list mints as a dependency, the compilation tried to build libdpd before the libint header was ready, hence the crash.  Running a test with the proper dependency in place now.

**Comment by lothian** [comment]
-j4 builds now run smoothly on my Mac and another cluster (cerebro), but I still have problems on one of our campus clusters.  The error is not the same as the libdpd+libmints case mentioned above, so I'm investigating.

**Comment by lothian** [comment]
I believe that the problems with -jN builds is now corrected.  Other errors I'm seeing arise from another bug that I'll put up in a separate issue report.
