### ISSUE TITLE
libpsio/filemanager.cc to_string() problem with Intel 15.3

### ISSUE THREAD

**Issue by lothian** [psi4/psi4public#220]
@bwb314 : Your recent update (a5facd8) to libpsio/filemanager.cc causes a build error with icpc 15.3:

    /home/crawdad/src/psi4/src/lib/libpsio/filemanager.cc(82): error: more than one instance of overloaded function "std::to_string" matches the argument list:
            function "std::to_string(long long)"
            function "std::to_string(unsigned long long)"
            function "std::to_string(long double)"
            argument types are: (int)
          std::string filenum = std::to_string(fileno);

std::to_string is C++11 and **should** accept an `(int)` argument, so I'm wondering if this is an inconsistent implementation in the Intel 15+ compiler.

**Comment by robertodr** [comment]
Is this on cerebro? We discussed this issue some time ago, since it's the same hiccup that hinders compilation of PCMSolver on cerebro. Intel relies on the standard headers from some installation of GCC. The only non-conflicting GCC on cerebro is 4.4.6 which implemented just those 3 overloads for `std::to_string`.

**Comment by lothian** [comment]
No, the build is clean on cerebro.  This is on blueridge, but perhaps it's
the same issue?  This change was just made on January 8th, which was after
we discussed the GCC header thing.

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by robertodr** [comment]
Yes, sorry. I meant blueridge.

**Comment by lothian** [comment]
Well, in this case, I can just cast to `(long long)` to get around the build error.  The PCMSolver issue is potentially more involved.
