### ISSUE TITLE
SAPT restart option request 

### ISSUE THREAD

**Issue by similt** [psi4/psi4public#226]
I am running expensive SAPT calculations and psi4 dies due to time limit.
My calculations reached upto " CHF Iterations converged " and then killed due to the 
time limit of my queue system. It is possible to add restart option to sapt ?

**Comment by jgonthier** [comment]
Hello,
thank you for your interest in Psi4. Adding restart capabilities to SAPT was already discussed in Issue 51 here. Unfortunately, it is going to take quite a bit of time to implement, and to my knowledge we do not have anyone with free time to do this right now.

Also, a better place to ask for new features is the Psi4 forum (http://forum.psicode.org), in the "new feature" section. Feel free to post something there so everyone knows there is interest in this.

**Comment by CDSherrill** [comment]
We are currently doing an upgrade to how information is passed around in Psi4.  This may make it easier in the future if we decide to add restart capabilities to SAPT.
