### ISSUE TITLE
Add support for the SMD continuum solvation method

### ISSUE THREAD

**Issue by Diazonium** [psi4/psi4public#227]
While PSI4 can perform PCM calculations, it does not have built in support for state of the art solvation models, like the SMD method by Cramer et al.
Paper:
http://pubs.acs.org/doi/abs/10.1021/jp810292n

**Comment by robertodr** [comment]
Thanks for your interest in Psi4. The SMD model offers an empirical parametrization of the nonelectrostatic contributions to the solvation energy (cavitation, dispersion, repulsion and hydrogen bonding effects) to add on top of the electrostatic contribution calculated by means of the IEFPCM or CPCM (COSMO) models. The nonelectrostatic contributions are added _a posteriori_ to the energy calculated self-consistently including the purely electrostatic reaction field. As such, SMD is very suitable for an independent implementation _via_ a Psi4 plugin. Both the IEFPCM and CPCM (COSMO) models are available in Psi4 using the interface to the PCMSolver library.

**Comment by CDSherrill** [comment]
Would be great if someone added this.  However, not elevating it to the level of a must-do item.

David

**Comment by tmcf22** [comment]
I could certainly use it. I am calculating 1-octanol/water partition coefficients with the SMD option in Gaussian. I bet you Psi4 adds the SMD capability in the next five years, or at least I hope they do.
