### ISSUE TITLE
torsion value uncomputable

### ISSUE THREAD

**Issue by loriab** [psi4/psi4public#231]
Input below gives error below. Should this happen, @psi-rking?

```

molecule innocentlookingwater {
O    0.00000000  0.00000000  0.00000000
H    0.16863830  0.60275550 -0.70533100
H   -0.76265500  0.37866910  0.40513500
O   -0.18467200  2.33422480  0.31265570
H    0.48244850  1.84992580  0.77377280
H   -0.08271400  3.22838610  0.58596930
}

set basis 6-31g

optimize('scf')
```

```
TORS::compute_val: unable to compute torsion value
Optimizer: Optimization failed!
```

**Comment by psi-rking** [comment]
With the fix from tonight, your dimer converges for me in 65 steps.  (It is a flat surface, and from a poor starting geometry, so a large number is not surprising.)

**Comment by ryanmrichard** [comment]
@loriab Lol "innocentlookingwater"

**Comment by loriab** [comment]
Fixed by https://github.com/psi4/psi4public/commit/1c1171835bf0442fdded9a60bb45f940e4b324b2
