### ISSUE TITLE
diatomic anharmonicity

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4public#234]
Hi Jet,

I try to use your diatomic code, which is available in psi4, with the following command:

phys_consts = anharmonicity(rvals, energies)

I got the following error:

NameError: name 'anharmonicity' is not defined

What is the correct syntax?

@jturney @loriab

**Comment by jturney** [comment]
Try adding to the top of your input file:

```
from diatomic import anharmonicity
```

Let me know if it works and I can add it to the default import list.

**Comment by bozkaya** [comment]
Thank you very much Jet, it works!
