### ISSUE TITLE
CMake doesn't autodetect -framework Accelerate on a Mac

### ISSUE THREAD

**Issue by jeffhammond** [psi4/psi4public#36]
I know how to fix this myself, but let's pretend I'm a stupid Mac user that has Xcode and, by the grace of god, managed to install gfortran without losing a limb.  Don't I deserve for CMake to throw me a bone and auto-detect the fast system BLAS/LAPACK?

I am surprised that CMake doesn't do this already btw.  Seems dirt-simple for them.

Cheers,

Jeff

Jeffs-MacBook-Pro:build jhammond$ cmake ..
-- The C compiler identification is Clang 4.2.0
-- The CXX compiler identification is Clang 4.2.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for MKL_Free_Buffers
-- Looking for MKL_Free_Buffers - not found
-- Looking for erf
-- Looking for erf - found
-- Looking for MPI_Finalize
-- Looking for MPI_Finalize - not found
-- Checking for restrict keyword
-- Checking for restrict keyword - __restrict__
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - not found
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
CMake Error at /usr/local/Cellar/cmake/2.8.12.1/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/2.8.12.1/share/cmake/Modules/FindLAPACK.cmake:142 (find_package)
  CMakeLists.txt:135 (find_package)

**Comment by CDSherrill** [comment]
We had a major cmake / math-detect revamp of the code recently.  Things should work more smoothly in the new version.

**Comment by loriab** [comment]
Actually, you still do have to pass ``--accelerate`` to ``setup``, as it's not on by default. @robertodr , is there a reason accelerate shouldn't be on by default for release builds?

**Comment by jturney** [comment]
We should not have to explicitly state the usage of the Accelerate
framework. The test for the system BLAS is sufficient as libblas.* and
liblapack.* both reference Accelerate. This has been the case for the last
several versions of Mac OS X. Is this not the case of other people's Macs?

-Jet

ls -l /usr/lib/libblas* /usr/lib/liblapack*
/usr/lib/libblas.dylib ->
../../System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
/usr/lib/liblapack.dylib ->
../../System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib


Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by dgasmith** [comment]
My laptops finds accelerate on Yosemite without any options set as well. Could this be a Xcode issue?

-Daniel Smith

**Comment by loriab** [comment]
Ok, my ``otool -L`` references ``Accelerate.framework`` also, w/o ever explicitly turning on ``--accelerate``. I guess the question for @robertodr then is why the flag is present in ``setup``. Then can re-close.

**Comment by robertodr** [comment]
Hi all. I added the flag to solve an issue both @lothian and I had when first moving to the new CMake build system. It might very well be that the flag was not needed in the first place! I am not a regular Mac user, at the time I just hardcoded a way to get Accelerate to be linked in.

**Comment by loriab** [comment]
It looks like ``setup --accelerate`` sets accelerate and turns off auto detecting blas/lapack. From all reports, accelerate is what is detected automatically with a plain installation. I guess the only use for the flag is when on a Mac there are multiple blas/lapack installations findable, and you want to quickly force the framework. I don't know any such complicated Macs in the connection, except perhaps this one at VaTech that inspired the flag. So how about (i) reclosing the issue, since accelerate is auto-detected, (ii) leave the ``--accelerate`` flag in setup for a while since it's doing no harm, (iii) stop actually passing that flag to setup on Macs and check the ``otool -L``.

**Comment by robertodr** [comment]
@loriab That's fine by me.

**Comment by jturney** [comment]
Sounds good to me, too.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA
