### ISSUE TITLE
Basis sets that span the periodic table

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4public#44]
For educational purposes it would be helpful to have some basis sets that span the periodic table (although obviously computations will be poor for heavier elements, especially without pseudopotentials).  Identify and enter such basis sets.

**Comment by loriab** [comment]
Ok, Nov 2014 (around https://github.com/psi4/psi4private/commit/986b28fdeabeabf43a79b08de5b5e79141719d84 ), the new basis set handling went in. When an auxiliary basis set isn't explicitly specified by the user (in fact explicitly setting is not reccommended as the internal defaults are superior), it looks on a per-atom basis (other def.) for the correct auxiliary basis for that orbital basis (e.g., `aug-cc-pvdz-ri` for `aug-cc-pvdz` and `cc-pvdz-ri` for `sto-3g`), then failing that uses ~ `def2-qzvpp` fitting basis sets. The def2's are defined through Kr w/o ECPs (psi4 has no ECPs), so you should never get an "auxilliary basis not available" for elements <=Kr. I think that's fulfilling our educational obligation. You still can get some oddities (see https://github.com/psi4/psi4public/issues/144), but the intent of this ticket is met.
