### ISSUE TITLE
Default basis sets on a per-atom basis

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4public#46]
If the user wants to run DF-MP2 on a molecule containing an element like Li or He, we need to use the requested basis set for most of the atoms and then a more generic basis set for the tricky atom.  It might be useful to let Python query basis set availability per atom --- apparently such queries are currently made C-side.

**Comment by psi4** [comment]
There's some docs and tests still to do, but the intent of this issue is satisfied as of Nov 2014.
