### ISSUE TITLE
compile problem with gcc4.4

### ISSUE THREAD

**Issue by sunqm** [psi4/psi4public#53]
I cannot use the default options provided by ../configure.cmake to finish compiling unless --with-ldflags='-lm' is added.  With the default options, it complains
gcc: : No such file or directory
during compiling of libint_compiler

My platform is gcc-4.4, cmake-2.8.2

**Comment by CDSherrill** [comment]
We've totally revamped the make system now.  Things should we working smoothly under the new system.
