### ISSUE TITLE
SAPT parallelisation query 

### ISSUE THREAD

**Issue by rxk900** [psi4/psi4public#57]
Hello,
One of our users hit a problem last year on our supercomputer with his SAPT (energy('sapt2+3-ct')) jobs. Our sysadmins flagged low cpu utilisation for his jobs for which we decided that 4 cpus would give him optimum efficiency. However, the jobs were large enough as to take > 1000 hours (also frowned upon by our sysadmins) so I was asked to look into whether he could make better parallel use of the processors.  We had some teething problems bringing our new supercomputer on line last year so I wanted to rule out issues on our side and I think I have now ruled out issues with IO, memory and threading (that had affected other programs).
Furthermore, during the investigations we noticed that "top" showed an almost equal alternation between one cpu and maximum cpus thus averaging above/below 50% use no matter how many cpus were requested. Roger Amos and I had a quick look at the SAPT papers and decided there wasn't anything intrinsic about the method that wouldn't allow it to parallel or would cause this behaviour (note I initially thought it might be a load imbalance between monomer basis and dimer basis calculations but it isn't). Also, subsequently we were asked to look into the performance of energy('fno-df-ccsd(t)') and that doesn't show this serial/parallel alternation.
Do you have any thoughts on this and have suggestions for determining optimum number of processors (does it depend on memory?) for this sort of calculation?
Thanks.
Rika
PS Do you need an input deck for this? Originally, the smallest case he had showing this behaviour took 230 hrs (seemed to be ok for his 60 hr SAPT job) but since then I think I have a 48 hr test case that will also display this behaviour. I'll need to ask the user for permission to pass it on first though.

**Comment by CDSherrill** [comment]
Sorry we haven't had an opportunity to follow up on this.  We need to do some general scaling tests with many of the parts of Psi4.  We tested SAPT0 more extensively than SAPT2+(3) in terms of scaling.  In general SAPT0 scales reasonably well at least up to 8 cores.  Would have expected similar results for SAPT2+(3) unless perhaps the I/O is beginning to have a serious effect.

**Comment by rxk900** [comment]
Not sure whether the group concerned are still working on this. I haven't looked at this since. However, I do remember it isn't IO as we took it through Darshan which is an IO profiler.
It did have a feel of load balancing.

**Comment by sykstan** [comment]
Hello all,
I am the aforementioned user that was having parallelism issues with SAPT2+3. First of all thank you to you all for your work on Psi4 :) And yes, our group is still interested in running SAPT calculations. After submitting another round of SAPT2 and feeling held back by the limit of 4 cpus, I thought perhaps the developers had made progress in the code. A quick Google led me here. Sorry I'm a year late to the discussion, but is there anything in the works with regards to high order SAPT?

**Comment by jgonthier** [comment]
Hello,

The short answer is, at the moment, no. As said above, nothing in these equations prevents parallelism, but the equations are extremely complex and so is the code...
Improving the parallelism of SAPT0, which is much simpler, is on the pipeline though.
Sorry we can't help more for now, but if you know someone who can code, contributions are welcome!

**Comment by sykstan** [comment]
Hi,

I'd be happy to help with code--it would be an interesting learning experience. But I'd probably only be able to find time after I finish my PhD.

**Comment by ryanmrichard** [comment]
If you do end up working on it, we would love to incorporate your codes; however, for the time being we are going to close this issue as our resident SAPT code expert will not have a chance to improve the load balancing anytime soon.
