### ISSUE TITLE
RHF gives wrong ground state determinant

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4public#63]
There are many ways to converge RHF, and sometimes you can get stuck in a local minmum, that's true. However, the following case is quite striking. My input:

--------------------------------------------------------------------------

molecule N2 {
N          0.000000000000     0.000000000000     0.000000000000
N          0.000000000000     0.000000000000     2.060000000000
units au
}

plugin_load("./mointegrals.so")

set basis sto-3g
set mointegrals print 1
set reference rhf

scf()

plugin("mointegrals.so")

--------------------------------------------------------------------------

I use the MO integrals for a subsequent FCI calculation (in a self-written program). When I start from the RHF determinant given by Psi4:

DOCC [     2,    0,    1,    0,    0,    2,    1,    1 ]
Total Energy =                       -106.7540443603229363

the FCI energy converges to the wrong answer. When I look at the energies from all possible determinants with Sz=0; irrep Ag; and N=14 electrons in the MO single-particle basis from Psi4, there is a determinant (in that MO basis!) with an energy which is lower: E = -107.488903265175 . The FCI energy then does converge to the right answer when this determinant is given as input for Davidson iterations.

**Comment by CDSherrill** [comment]
We will try to write a more robust default guess in the future.
