### ISSUE TITLE
DiskJK

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4public#65]
Hi,

I'm using DiskJK in a plugin: https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrgci.cc#L292 . Does it reuse the existing disk AO integrals or does it recompute them? In case of the latter: How do I avoid this? Is there a way to fetch the JK from the wavefunction object or the environment?

Thank you for your time and answer!
Best,
Sebastian

**Comment by robparrish** [comment]
Yes, the integrals are recomputed every time a new DiskJK is built. There
is presently no way to avoid this. If you are being hamstrung by the AO
integrals, I recommend a DFJK object or perhaps a DirectJK object.

Best,

-Rob
