### ISSUE TITLE
Two-particle density matrix in AO basis after full-CI calculation

### ISSUE THREAD

**Issue by genogator** [psi4/psi4public#67]
It is clear to me that, after a full-CI calculation, is possible to print out the two-particle density matrix (2PDM) in MO basis, BUT  it is not clear to me if psi4 also allows to print out the 2PDM in AO basis.

Could someone help me to solve this problem, please? I really need the 2PDM in AO basis!

Thanks in advance!

PS: this is the input file I am struggling with:

memory 256 mb

molecule h2o {
   O
   H 1 0.96
   H 1 0.96 2 104.5
}

plugin_load("/auto/store/ale/PSI/objdir/plugins/backtrans/backtrans.so")

set   basis 6-31G
set   print 5
set   OPDM true
set   OPDM_PRINT true
set   TPDM true
set   TPDM_PRINT true
energy('fci')

plugin("/auto/store/ale/PSI/objdir/plugins/backtrans/backtrans.so")

**Comment by CDSherrill** [comment]
The short answer is that there's not a built-in way to do this.  However, it shouldn't be too hard to backtransform the TPDM for some small case.  The default backtransform in plugins/backtrans/ is not smart enough to know about the CI ordering of the MO's, so it won't work as-is.

Perhaps if someone on the team has a little time on their hands they might look into this more.

David

**Comment by CDSherrill** [comment]
Actually we used to be able to do things like this with the old transqt or transqt2 codes, but we haven't been using them for backtransforms lately.
