### ISSUE TITLE
sointegrals is missing integrals?

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4public#68]
I've build the default `sointegrals` plugin and used it on the following input file:
```
molecule CO
{
    C
    O 1 1.14
    units au
}

set {
    basis sto-3g
}

plugin_load("./sointegrals.so")

set sointegrals {
    print 10
}

plugin("sointegrals.so")
```
This is the output: https://gist.github.com/wpoely86/15abc32a634c0cc4a73f

I think something went wrong. `CO` has `c2v` symmetry here. If I look at the TEI, I'm missing `(2 0 | 0 0)`. Both orbital 0 and 2 are part of the `A1` irrep and so on basis of symmetry, I don't expect this integral to be zero. If I run exactly the same molecule with the `mointegrals` plugin (and symmetric orthogonalisation, so `nmo`==`nso`.), then it does give me the `(2 0 | 0 0)` integral.
The `(0 0 | 0 0)`, `(1 0 | 0 0)`, `(3 0 | 0 0)`, `(4 0 | 0 0)` and `(5 0 | 0 0)` integrals are all present.

**Comment by wpoely86** [comment]
OK, found it. The overlap is zero for those orbitals.

But I was under the impression that `sointegrals` gave me all unique integrals because of symmetry, including those that are zero due to the overlap. This should be made clearer in the docs.

**Comment by jturney** [comment]
The numbers printed by the sointegral plugin are not the symmetry blocked
indices but the absolute indices (non-symmetry blocked). The order of the
absolute indices come directly from the basis set. For your input file the
the "2" index actually belongs to B1 irrep (2px on carbon) whereas "0" is
A1 (1s on carbon), so by symmetry this integral does not exist. The
transformation matrix for obtaining symmetry blocked integrals is obtained
with:

// prints the transformation matrix.
soBasis->petite_list()->sotoao()->print();

What you probably want to look into is printing the {p,q,r,s}irrep and
{p,q,r,s}so values in the ERIPrinter class in your plugin. These values are
post-symmetry-blocking-transformation.

You're right, the difference between absolute and symmetry blocked indices
could be better explained. With respect to two-electron integrals, Psi
never reports integrals of value zero to prevent wasting CPU cycles, again
this could be made clearer.


Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by jturney** [comment]
Actually after double checking I was completely wrong on the symmetry
explanation. Sorry for any confusion I caused.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by wpoely86** [comment]
The indices printed are the absolute symmetry indices right? If it isn't the case, then I don't understand the results I'm getting :wink:

**Comment by jturney** [comment]
You're right, they are absolute symmetry indices. I had it in my head that
they were absolute in terms of the atomic orbitals. Like you said, it is
zero because of overlap.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA
