### ISSUE TITLE
the 'I'  element should  adopt what basis set

### ISSUE THREAD

**Issue by autolife** [psi4/psi4public#76]
http://sirius.chem.vt.edu/psi4manual/latest/basissets_byelement.html#apdx-basiselement

my molecule  complex have 'I' atom, 
the complex was optimized by g09 at MP2/AUG-CC-PVDZ,and the 'I' (AUG-CC-PVDZ-PP),

NOW I want to decompose the interact energy by the psi4 software,but it didn't have basis set support the 'I'  element.

can you give me some suggestions?

**Comment by ryanmrichard** [comment]
The unfortunate answer is Psi4's support for atoms past krypton (perhaps a bit optimistic) is very limited.  In short this stems from our inability to handle effective core potentials.  We are currently discussing how to better address this for the next major release of Psi4, which is likely a long ways away; however, in the meantime I think what you want to do is not possible with Psi4.  My recommendation is to consider the Q-Chem package, which is also capable of performing SAPT (energy decomposition) and does have support for atoms past krypton.

**Comment by autolife** [comment]
thank you
