### ISSUE TITLE
Plugin examples gone

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4public#78]
Dear all,

I have built the latest version of psi4 with plugins:

    BLA_VENDOR=Intel10_64lp CXX=icpc CC=icc cmake .. -DENABLE_PLUGINS=ON -DENABLE_DUMMY_PLUGIN=ON

and can create new plugins and compile them. However, the old examples, typically in the folder

    /path/to/source/psi4/objects/plugins/

are not generated anymore. I don't know if this was intentional?

Best regards,
Sebastian

**Comment by loriab** [comment]
No, that wasn’t intentional. If it’s new since ~12 days ago, it probably has to do with removal of the Makefile system. In any case, should integrate the plugins better with cmake and make them test cases again so that we know when they break. Thanks for the notice.

Lori

**Comment by loriab** [comment]
Ok, the example plugins build automatically again and are incorporated into the testing system. The ``-DENABLE_PLUGINS`` option, btw, only controls whether these example plugins are built automatically, as opposed to in earlier build schemes where it actually controlled whether ``-fpic`` was used.
