### ISSUE TITLE
Python argument types error with embedded basis set data

### ISSUE THREAD

**Issue by mattbernst** [psi4/psi4public#79]
Normally Psi4 gives me helpful error messages but in this case I have poked around a bit and can't figure out how to fix my input. I'm trying to create input files with all basis data supplied from within the file itself, so old jobs are self-documenting. I am trying to run the input below with the latest binary installed via conda. It crashes with the message

```
Traceback (most recent call last):
  File "<string>", line 59, in <module>
Boost.Python.ArgumentError: Python argument types in
    psi4.scf(str)
did not match C++ signature:
    scf(void)
    scf(P7_object, P7_object)
```

Here is the input I am trying to run. I've made some mistake trying to implement what I read in the docs, but I can't figure out what. I retrieved the basis set data in Gaussian 94 format from the EMSL Basis Set Exchange.

```
#methane test

molecule {
  #charge multiplicity
  0 1
  C0	0.000000	0.000000	0.000000
  H0	1.092199	0.000000	-0.000001
  H0	-0.364063	0.138497	1.020380
  H0	-0.364067	-0.952923	-0.390247
  H0	-0.364068	0.814425	-0.630132
}

set globals {
  reference RHF
  maxiter 999
}

basis {
  assign C0 C0bas
  assign H0 H0bas
  #C 3-21G
  [ C0bas ]
  cartesian
  ****
  C     0 
  S   3   1.00
      172.2560000              0.0617669        
       25.9109000              0.3587940        
        5.5333500              0.7007130        
  SP   2   1.00
        3.6649800             -0.3958970              0.2364600        
        0.7705450              1.2158400              0.8606190        
  SP   1   1.00
        0.1958570              1.0000000              1.0000000        
  ****
  #H 3-21G
  [ H0bas ]
  cartesian
  ****
  H     0 
  S   2   1.00
        5.4471780              0.1562850        
        0.8245470              0.9046910        
  S   1   1.00
        0.1831920              1.0000000        
  ****
}

scf('energy')
```

**Comment by andysim** [comment]
Matt,

You accidentally typed

scf(‘energy’)

instead of

energy(‘scf’)

Normally you’d get a more useful python error related to calling an undefined function but, unfortunately, the scf function does exist in this case so you got a more obscure error message.

Andy.

**Comment by mattbernst** [comment]
What a goof. Thanks for spotting the obvious. I had spent so long on the basis data that I missed the real problem!
