### ISSUE TITLE
CMake Error Overhaul

### ISSUE THREAD

**Issue by ryanmrichard** [psi4/psi4public#82]
I presume I'm not the only one this happens to, but when CMake generates an error during setup, the error is often obscured and hidden in the wealth of output.  Instead of simply printing: "Error Occurred" (or whatever it actually prints) and then having to scour the output I'm wondering if it would be possible to somehow re-echo the error at the bottom of the output.  I'll look into this, but if one of the CMake gurus already knows how to do this, I'd appreciate any insight you can give.

**Comment by SebWouters** [comment]
If an error occurs, it occurs again when you call "make". So if you now call "make VERBOSE=1" instead, you should get the specific info you're looking for.

**Comment by ryanmrichard** [comment]
That  works perfectly.  In my book, this is another reason for combining the setup and build into one step then, either way I'm going to close this issue.
