### ISSUE TITLE
HEAD build failure with gcc 4.4.6

### ISSUE THREAD

**Issue by mj-harvey** [psi4/psi4public#85]
Hi,
When building the current HEAD with gcc 4.4 (RHEL6 equivalent platforms), the build fails in Timer.cc, due to the use of a C++ feature in Table.h that's not supported by that compiler:

```
...
 [52%] Building CXX object src/lib/libPsiUtil/CMakeFiles/PsiUtil.dir/Implementations/Timer.cc.o
In file included from /export71/home/mjharvey/psi4public/psi4public/src/lib/libPsiUtil/Implementations/Timer.cc:24:
/export71/home/mjharvey/psi4public/psi4public/src/lib/libPsiUtil/Implementations/../Table.h:142: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/export71/home/mjharvey/psi4public/psi4public/src/lib/libPsiUtil/Implementations/../Table.h: In constructor ‘psi::Table<T, Args>::Table(int, int, int, const T&, Args& ...)’:
/export71/home/mjharvey/psi4public/psi4public/src/lib/libPsiUtil/Implementations/../Table.h:216: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
```

**Comment by ryanmrichard** [comment]
@Harvey the immediate answer is you need to update your compiler; however
the repeated reoccurance of this problem suggests it may be necessary to
revisit the decision to use C++11.

@developers what versions of compilers are we willing to support?  The
decision to start using C++11 limits us to Intel15 for full compliance (or
Intel13 for about 90% compliance). For the GCC line 4.4 gives us about 90%
compliance and 4.8 full compliance.  Clang 2.9 is 90% and they claim 3.3
for full support,  but I'm confused by their caveat of them not having to
provide support for two features.  This suggests to me that they still are
not at full compliance and never will be.

The argument that we should wrap our C++11 code with macros only works if
that code could've been written with C++98.  In my experience achieving the
same effect as a variadic templates is in general impossible.  You can
write a recursive normal template, with default dummy parameters to achieve
a similar result by using many template specializations.   This however is
limited to about 10-20 parameters (depending on the compiler); variadic
templates extend this to an arbitrary number.  This is why the boost tuple
is limited to 10 parameters.  And yes there are reasons to need more than
10 parameters.  I've needed up to 118 (the number of atoms).

Rvale references are probably the only other feature I'd argue for as not
supporting rvalue references may require extensive code design, but 9 nice
that design has been done they can be easily simulated by an unique
pointer.  Shared pointers, new time system, new random number generators
are all in Boost.  Lamdas are syntactic sugar for static functions.  Strong
enums are just enums each in their own namespace.  Intializer lists for
primitive data types have always existed and can be passed as pointers to
more complicated objects.
