### ISSUE TITLE
psi4 very very slow to start

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4public#89]
```bash
$ time psi4 --help

real	0m5.980s
user	0m1.279s
sys	0m4.693s
```
This is done with b8a2f55b719d3. Why is psi4 so extremely slow to start? I have it both with g++/4.9.2 and icpc/2015.0.090 on multiple computers. As it is the sys time that is very high, I've used strace which tells me:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.99    3.413450           1   5057853           times
  0.01    0.000177           4        43           mmap
  0.00    0.000082           2        37           brk
  0.00    0.000079          79         1           execve
  0.00    0.000071           4        16           close
  0.00    0.000032           2        18           fstat
  0.00    0.000018           1        30           mprotect
  0.00    0.000016           1        15           open
  0.00    0.000015          15         1         1 access
  0.00    0.000000           0        14           read
  0.00    0.000000           0         1           munmap
  0.00    0.000000           0         2           rt_sigaction
  0.00    0.000000           0         1           rt_sigprocmask
  0.00    0.000000           0         2           getdents
  0.00    0.000000           0         1           getrlimit
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         2           futex
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           openat
  0.00    0.000000           0         1           set_robust_list
------ ----------- ----------- --------- --------- ----------------
100.00    3.413940               5058042         1 total
```
Too much time sampling?

**Comment by jturney** [comment]
Very interesting. I had noticed slow startup times as well just hadn't had a chance to look into it. I'll see what I can figure out.

**Comment by ryanmrichard** [comment]
That's my new timer object.   At startup it determines the uncertainty in
each time, on each mpi process, via sampling.

**Comment by robparrish** [comment]
https://www.youtube.com/watch?v=vQy9SJIaN38

-Rob

**Comment by wpoely86** [comment]
@ryanmrichard any reason the `high_resolution_clock` of C++11 isn't good enough? Or maybe you should just do it a in a different thread?

**Comment by ryanmrichard** [comment]
I'm learnimg the world isn't ready for C++11 yet, and I'm in the process of
phasing it out of my codes.  Anyways, my timer relies on Boost.  What I do
is ripped right out of the Boost example for how to determine the
uncertainty in their timers, the sampling rate may be a bit high if there
ends up being 5000000 calls though.  I'm not sure what you mean exactly by
separate thread.  The uncertainty in each timer is a hardware feature so on
a heterogeneous cluster each mpi process needs to sample.  This is only
done once at startup.

**Comment by robparrish** [comment]
Yeah, it just needs to be turned into a user-option (defaulted off).

-Rob

**Comment by wpoely86** [comment]
I don't agree with the world not being ready for C++11. More and more projects are defaulting to C++11 and that's a good thing. But using Boost in this case is equivalent. 
With a separate thread I mean: make it non-blocking. But a user-option is also just fine for me.

**Comment by ryanmrichard** [comment]
Default off seems silly if we report times.  The user has a right to know
how accurate those times are.  If 5 seconds really bothers everyone I vote
for a timing flag that enables/disables all timings.  I think that's the
wrong approach though and it makes more sense to examine the sampling
parameters of the timer.

**Comment by robparrish** [comment]
Many users start Psi hundreds to thousands of times for certain types of
applications studies, with each job taking a few seconds. Now we are
potentially doubling that time.

-Rob

**Comment by ryanmrichard** [comment]
Look at some of the other issues on this wiki.  Numerous people are
compiling Psi4 with almost 10 year old compilers. I get it though, once you
have a cluster running you don't want to touch anything in case you break
it. In my experience your average super computer on the otherhand is a year
or two out of date. Compilers like Intel, that I swear by, only are fully
C++11 compliant with the most recent releases.

**Comment by wpoely86** [comment]
And if you're testing stuff and playing around, that 5 seconds is also very very annoying. 

But again, any reason why simply using `high_resolution_clock` from Boost/C++11 isn't good enough? On most systems, the accuracy will be more then enough for practical purposes. The actual sampling to determine the accuracy can be activated by a user-option?

**Comment by ryanmrichard** [comment]
It's been awhile since I made that class but I seem to recall the high res timers simply report time in nanoseconds,  they aren't necessarily that accurate. I'll look into this more tomorrow.

Also I didn't realize so many users are running such short jobs.  It would be interesting to make a wiki page where groups posted what features of Psi4 they use along with typical applications.   This data would be very interesting in terms of code design and would allow better tailoring to their needs.

**Comment by jturney** [comment]
Perhaps it's just me but I really don't care how accurate the timers are and I'm not even an average user. If it's a few nanoseconds off I really don't care. Even on my system the resolution of the `high_resolution_clock` is 1 ns. I'm only going to use our internal timers to give me a ballpark estimate.

If I'm really concerned with profiling Psi4 I'm not going to use our internal timers to do that, I'll turn to other tools for that like Instruments on Mac or Intel VTune on Linux.

**Comment by ryanmrichard** [comment]
My sincerest apologies to the Psi4 community, I didn't even begin to fathom that these timers were going to be such a fiasco.  I dropped the sampling down to 1 point per timer so I expect they should be invisible now, but I can't confirm this at the moment.  If someone wants to check this and close the issue if it's been resolved I would appreciate it.  In the meantime I'll have to look into VTune as it appears to do everything I was making these timers do, but with a pretty GUI interface.

**Comment by wpoely86** [comment]
Confirmed, with 521f06adb4, it's fast again.

@ryanmrichard definitely check out VTune. Amplifier, Perfexpert, ggprof, perf are also nice.
As for your previous question: I use Psi mostly as a framework for my own code. I let it do stuff (like, calc mo integrals) and use it in my own code.

And on your previous previous point, 10 year old compiler just suck. There are slow compared to the latest and the greatest. You should not expect everything to still work if you use such old software. For HPC sites, there are great tools like [Easybuild](https://hpcugent.github.io/easybuild/) (which supports Psi btw).
