### ISSUE TITLE
Issue in detci with multiple molecules

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4public#92]
Input file:
```python
import molutil

molecule h2o {
0 1
O
H 1 r
H 1 r 2 104.479848
units angstrom
}

molecule beh2 {
0 1
Be 0 0 0 
H 0 0 r
H 0 0 -r
units angstrom
}

set basis sto-3g

beh2.r=1
molutil.activate(beh2)
energy('fci')

h2o.r=1
molutil.activate(h2o)
energy('fci')
```
will calculate the FCI energy of the BeH<sub>2</sub> molecule, then do the RHF of H<sub>2</sub>O but at start of the detci module it will give:
```python
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "/home/ward/opt/share/psi/python/driver.py", line 576, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/home/ward/opt/share/psi/python/proc.py", line 1975, in run_detci
    psi4.detci()
RuntimeError: (matrix_element): nalp/nbet != init_nalp/nbet
```
Seems like something should be reinitialized after activating a new molecule. Done with 521f06adb441ac1e2f1732eb1cd090190b409c49.

**Comment by loriab** [comment]
Try sticking a clean() between the two calcs. There were some reasons we didn’t want to force this but instead leave it to the user/programmer. See if that helps.

Lori

**Comment by wpoely86** [comment]
Hi Lori,

I've already tried that. Doesn't help.

**Comment by CDSherrill** [comment]
I'll have a look.

David

**Comment by ryanmrichard** [comment]
This appears to be fixed with the new CI code, which is part of the current GitHub version.  If problems persist please feel free to reopen.
