### ISSUE TITLE
undefined reference to `PyUnicodeUCS4_FromEncodedObject'

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4public#94]
Dear Pis4 developers.

I've got in issue when link psi4 binary:
```
/usr/local/lib/libpython2.7.a(posixmodule.o): In function `posix_tmpnam':
/home/kbob/bin/Python-2.7.5/./Modules/posixmodule.c:7515: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/usr/local/lib/libpython2.7.a(posixmodule.o): In function `posix_tempnam':
/home/kbob/bin/Python-2.7.5/./Modules/posixmodule.c:7462: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/home/kbob/git/psi4release/build/boost/lib/libboost_python-1_57.a(builtin_converters.o): In function `boost::python::converter::(anonymous namespace)::slot_rvalue_from_python<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, boost::python::
builtin_converters.cpp:(.text+0x1286): undefined reference to `PyUnicodeUCS4_AsWideChar'
/home/kbob/git/psi4release/build/boost/lib/libboost_python-1_57.a(builtin_converters.o): In function `encode_string_unaryfunc':
builtin_converters.cpp:(.text+0x455): undefined reference to `PyUnicodeUCS4_FromEncodedObject'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/psi4] Ошибка 1
make[1]: *** [src/bin/psi4/CMakeFiles/psi4.dir/all] Ошибка 2
make: *** [all] Ошибка 2
```

I'm running on Ubuntu 14.04 with cmake installed from ppa:george-edison55/cmake-3.x

Since the default version available in 14.04 is boost-1.54, used to compile boost_1_57_0.tar.bz2 that included in distro.
http://packages.ubuntu.com/trusty/libboost-all-dev

My python interpreter support UCS-4.

python -c "import sys; print(sys.maxunicode)"
returns 1114111

python3 -c "import sys; print(sys.maxunicode)"
returns 1114111

Could you clarify my issue or can I compile Psi4 without puthon support to avoid this issue?
in particular, I only need to generate MOLDEN file from SCF calculations.

With respect, Vladimir.

**Comment by loriab** [comment]
I've seen similar errors when Python versions are mixed. Use which python and which python-config to check your shell versions. Use ldd bin/psi4 to check the linked version. Boost also could have been built against a diff Python. If there's any mismatch identified or possible, try passing --python to setup (setup --help for details) and letting psi4 build the packaged boost. No turning off Python for psi4, I'm afraid. It's integral to the executable.

**Comment by Konjkov** [comment]
Yes, it was so. Python versions were mixed.
