### ISSUE TITLE
symbol error

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4public#96]
Dear all, 

I added a new plugin into PSI4 (the newest psi-master code from github) (dmrgscf plugin), but 
when running psi4 on the input.dat file, i obtain the following error :

symbol lookup error: /home/luca/psi-master/psi4public/plugins/mypsi4plugins/dmrgscf/dmrgscf.so: undefined symbol: _ZN7CheMPS26Irreps12getGroupNameEi
------------------------------------------------------------------------------------------------------------
my input file is :
------------------------------------------------------------------------------------------------------------
molecule O2 {
  O       0.0   0.0   0.0
  O       0.0   0.0   3.0 
units au
}

plugin_load("/home/luca/psi-master/psi4public/plugins/mypsi4plugins/dmrgscf/dmrgscf.so")

set basis     cc-pVDZ
set reference rhf

set dmrgscf wfn_irrep            0
set dmrgscf wfn_multp            1
set dmrgscf frozen_docc          [ 1 , 0 , 0 , 0 , 0 , 1 , 0 , 0 ]
set dmrgscf active               [ 2 , 0 , 2 , 2 , 0 , 2 , 2 , 2 ]

set dmrgscf dmrg_states          [   500,  1000,  1000 ]
set dmrgscf dmrg_econv           [ 1e-10, 1e-10, 1e-10 ]
set dmrgscf dmrg_maxsweeps       [     5,     5,    10 ]
set dmrgscf dmrg_noiseprefactors [  0.05,  0.05,   0.0 ]
set dmrgscf dmrg_print_corr      false
set dmrgscf mps_chkpt            false

set dmrgscf dmrgscf_convergence  1e-6
set dmrgscf dmrgscf_store_unit   true
set dmrgscf dmrgscf_do_diis      true
set dmrgscf dmrgscf_diis_branch  1e-2
set dmrgscf dmrgscf_store_diis   true

set dmrgscf dmrgscf_max_iter     100
set dmrgscf dmrgscf_which_root   2   # First excited state
set dmrgscf dmrgscf_state_avg    true
set dmrgscf dmrgscf_active_space NO  # INPUT; NO; LOC
set dmrgscf dmrgscf_loc_random   false

scf()

plugin("dmrgscf.so")

------------------------------
Best wishes
LUCA

**Comment by SebWouters** [comment]
Hi Luca,

Can you check with
  $ ldd dmrgscf.so
that (1) it looks for libchemps2.so
and (2) it finds libchemps2.so?

(If you could paste the output from that command.)

Best,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 

Problem is now solved. Just one has to give: 
-L/home/luca/psi-master/CheMPS2/build/binbin/lib64   AND   -lchemps2

ALLTHE BEST
LUCA
